package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/northcutted/clearcutt/internal/fleet"
)

// writeTempFleetConfig marshals the default config to a temp file and returns
// its path plus a temp core directory for generated output.
func writeTempFleetConfig(t *testing.T) (configPath, coreDir string) {
	t.Helper()
	dir := t.TempDir()
	raw, err := fleet.Marshal(fleet.DefaultConfig("acme", "platform"))
	if err != nil {
		t.Fatalf("marshal default config: %v", err)
	}
	configPath = filepath.Join(dir, "clearcutt.fleet.yaml")
	if err := os.WriteFile(configPath, raw, 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return configPath, filepath.Join(dir, "core")
}

func TestFleetCompileWritesGeneratedMatrix(t *testing.T) {
	configPath, coreDir := writeTempFleetConfig(t)

	if _, err := runCLI(t, "fleet", "compile", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile: %v", err)
	}

	matrixPath := filepath.Join(coreDir, "lib", "fleet-matrix.nix")
	raw, err := os.ReadFile(matrixPath)
	if err != nil {
		t.Fatalf("expected generated %s: %v", matrixPath, err)
	}
	body := string(raw)
	for _, want := range []string{
		"Generated by `clearcutt fleet compile`",
		"closurePurityTargets = [",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("generated matrix missing %q", want)
		}
	}

	// Derive the expected cells from the config rather than hardcoding runtime
	// lines. Pinning literal lines here made this test a second place the fleet
	// matrix had to be edited, and it failed for the wrong reason every time the
	// fleet legitimately changed shape. What matters is the invariant: every
	// configured (line, tier) is emitted, with the fields the flake reads.
	cfg := fleet.DefaultConfig("acme", "platform")
	for _, line := range cfg.Matrix.Languages {
		for _, tier := range cfg.Matrix.Tiers {
			want := fmt.Sprintf(`{ line = "%s";`, line)
			if !strings.Contains(body, want) {
				t.Errorf("generated matrix missing a cell for line %q:\n%s", line, body)
				continue
			}
			if !strings.Contains(body, fmt.Sprintf(`tier = "%s";`, tier)) {
				t.Errorf("generated matrix missing tier %q for line %q", tier, line)
			}
		}
	}
	// Every cell carries the lifecycle block the flake reads; a cell without it
	// evaluates to an error at nix time, not here.
	if got := strings.Count(body, "lifecycle = {"); got != len(cfg.Matrix.Languages)*len(cfg.Matrix.Tiers) {
		t.Errorf("expected %d lifecycle blocks (%d lines x %d tiers), got %d",
			len(cfg.Matrix.Languages)*len(cfg.Matrix.Tiers), len(cfg.Matrix.Languages), len(cfg.Matrix.Tiers), got)
	}
}

func TestFleetCompileCheckDetectsDrift(t *testing.T) {
	configPath, coreDir := writeTempFleetConfig(t)

	if _, err := runCLI(t, "fleet", "compile", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile: %v", err)
	}

	// A freshly generated file passes --check.
	if _, err := runCLI(t, "fleet", "compile", "--check", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile --check on fresh file: %v", err)
	}

	// Tampering with the file makes --check fail.
	matrixPath := filepath.Join(coreDir, "lib", "fleet-matrix.nix")
	if err := os.WriteFile(matrixPath, []byte("# drift\n"), 0o644); err != nil {
		t.Fatalf("tamper: %v", err)
	}
	if _, err := runCLI(t, "fleet", "compile", "--check", "--fleet-config", configPath, "--core-dir", coreDir); err == nil {
		t.Fatal("expected fleet compile --check to fail on a drifted file")
	}
}
