package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/northcutted/clearcutt/internal/fleet"
)

// writeTempFleetConfig marshals the default config to a temp file and returns
// its path plus a temp core directory for generated output.
func writeTempFleetConfig(t *testing.T) (configPath, coreDir string) {
	t.Helper()
	dir := t.TempDir()
	raw, err := fleet.Marshal(fleet.DefaultConfig("acme", "platform"))
	if err != nil {
		t.Fatalf("marshal default config: %v", err)
	}
	configPath = filepath.Join(dir, "clearcutt.fleet.yaml")
	if err := os.WriteFile(configPath, raw, 0o644); err != nil {
		t.Fatalf("write config: %v", err)
	}
	return configPath, filepath.Join(dir, "core")
}

func TestFleetCompileWritesGeneratedMatrix(t *testing.T) {
	configPath, coreDir := writeTempFleetConfig(t)

	if _, err := runCLI(t, "fleet", "compile", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile: %v", err)
	}

	matrixPath := filepath.Join(coreDir, "lib", "fleet-matrix.nix")
	raw, err := os.ReadFile(matrixPath)
	if err != nil {
		t.Fatalf("expected generated %s: %v", matrixPath, err)
	}
	body := string(raw)
	for _, want := range []string{
		"Generated by `clearcutt fleet compile`",
		`{ line = "python3.14"; language = "python"; version = "3.14"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }`,
		`{ line = "go1.26"; language = "go"; version = "1.26"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }`,
		"closurePurityTargets = [",
		"runtimePatchTargets = [",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("generated matrix missing %q", want)
		}
	}
}

func TestFleetCompileCheckDetectsDrift(t *testing.T) {
	configPath, coreDir := writeTempFleetConfig(t)

	if _, err := runCLI(t, "fleet", "compile", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile: %v", err)
	}

	// A freshly generated file passes --check.
	if _, err := runCLI(t, "fleet", "compile", "--check", "--fleet-config", configPath, "--core-dir", coreDir); err != nil {
		t.Fatalf("fleet compile --check on fresh file: %v", err)
	}

	// Tampering with the file makes --check fail.
	matrixPath := filepath.Join(coreDir, "lib", "fleet-matrix.nix")
	if err := os.WriteFile(matrixPath, []byte("# drift\n"), 0o644); err != nil {
		t.Fatalf("tamper: %v", err)
	}
	if _, err := runCLI(t, "fleet", "compile", "--check", "--fleet-config", configPath, "--core-dir", coreDir); err == nil {
		t.Fatal("expected fleet compile --check to fail on a drifted file")
	}
}
