package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/northcutted/clearcutt/internal/fleet"
	"github.com/spf13/cobra"
)

// The runtime-patch completeness gate (core/tests/runtime-dep-floor.json) is the
// security keystone of runtime-scoped CVE patching: closure-cve-check.py and its
// Go port default-deny any shipped openssl/sqlite store path whose IDENTITY is
// not on the committed known-good allowlist. This generator RESOLVES those
// identities — it evaluates the flake's `cryptoIdentities` output (pure eval, no
// build) to learn the exact store paths of the crypto-overlaid openssl/sqlite
// across every shipped crypto set (the main pin plus the .NET and node unstable
// pins), stamps each with provenance (pin + locked rev + output + version), and
// writes the allowlist. Same lock -> same store paths, so the file generated
// locally matches the realized closure the gate walks in CI.
//
// Provenance, not version. The retired generator derived a numeric floor from
// CVE evidence; this one asserts patch-state by identity. The risk policy still
// chooses the cryptoTrust mode recorded in the file (nixpkgs default / reproduce
// opt-in); WHICH packages are crypto-tracked is the runtimeCryptoOverlay's
// decision, surfaced through `cryptoIdentities`.

const runtimeFloorDefaultFlakeDir = "core"
const runtimeFloorDefaultOut = "core/tests/runtime-dep-floor.json"
const runtimeFloorDefaultSystems = "x86_64-linux,aarch64-linux"
const runtimeFloorSchemaVersion = "clearcutt.runtime-crypto-allowlist/v1"

const runtimeFloorComment = "Runtime-patch completeness allowlist: the known-good store-path IDENTITIES of CVE-remediated crypto (openssl/sqlite) that may ship inside a production image closure. GENERATED by `clearcutt remediation generate-crypto-allowlist` (which evaluates the flake's cryptoIdentities output) — do not hand-edit; rebuild the patched crypto and regenerate. closure-cve-check.py and its Go port read deps[].knownGood[].storePath and default-deny any shipped openssl/sqlite whose identity is absent (provenance, not version: a patched-not-bumped openssl passes by identity; an unvetted higher version fails)."

type runtimeFloorFlags struct {
	flakeDir   string
	out        string
	systems    string
	policyJSON string
	check      bool
}

var runtimeFloorOpts runtimeFloorFlags

// CryptoIdentity is one resolved crypto store path with provenance, as emitted by
// the flake's `cryptoIdentities.<system>` output.
type CryptoIdentity struct {
	Name      string `json:"name"`
	CVE       string `json:"cve"`
	System    string `json:"system"`
	Pin       string `json:"pin"`
	Rev       string `json:"rev"`
	Output    string `json:"output"`
	Version   string `json:"version"`
	StorePath string `json:"storePath"`
}

// CryptoKnownGood is one allowlisted identity in the written file. The gate reads
// StorePath; the rest is recorded provenance/evidence.
type CryptoKnownGood struct {
	StorePath string `json:"storePath"`
	System    string `json:"system"`
	Output    string `json:"output"`
	Version   string `json:"version"`
	Pin       string `json:"pin"`
	Rev       string `json:"rev"`
}

// CryptoAllowlistDep is one tracked crypto dep and its known-good identities.
type CryptoAllowlistDep struct {
	Name       string            `json:"name"`
	CVE        string            `json:"cve"`
	Provenance string            `json:"provenance"`
	KnownGood  []CryptoKnownGood `json:"knownGood"`
}

// CryptoAllowlistFile is the generated runtime-dep-floor.json. Only deps[].name
// and deps[].knownGood[].storePath are read by the gate; everything else is
// recorded evidence.
type CryptoAllowlistFile struct {
	Comment       string               `json:"comment"`
	SchemaVersion string               `json:"schemaVersion"`
	GeneratedBy   string               `json:"generatedBy"`
	Trust         string               `json:"trust"`
	Deps          []CryptoAllowlistDep `json:"deps"`
}

// cryptoIdentityResolver resolves the known-good crypto identities for a system.
// The nix-eval implementation is the real path; tests inject a fake.
type cryptoIdentityResolver interface {
	Resolve(system string) ([]CryptoIdentity, error)
}

// nixEvalResolver evaluates `<flakeDir>#cryptoIdentities.<system>` and decodes
// the JSON. Pure evaluation — no build — so it resolves linux store paths even
// on a Darwin host (same lock -> same paths as CI).
type nixEvalResolver struct {
	flakeDir string
	runJSON  func(args ...string) ([]byte, error)
}

func newNixEvalResolver(flakeDir string) nixEvalResolver {
	return nixEvalResolver{
		flakeDir: flakeDir,
		runJSON: func(args ...string) ([]byte, error) {
			cmd := exec.Command("nix", args...)
			cmd.Stderr = os.Stderr
			return cmd.Output()
		},
	}
}

func (r nixEvalResolver) Resolve(system string) ([]CryptoIdentity, error) {
	attr := fmt.Sprintf("%s#cryptoIdentities.%s", flakeRef(r.flakeDir), system)
	raw, err := r.runJSON("eval", "--no-warn-dirty", "--json", attr)
	if err != nil {
		return nil, fmt.Errorf("nix eval %s failed: %w (is nix installed and the flake evaluable?)", attr, err)
	}
	var ids []CryptoIdentity
	if err := json.Unmarshal(raw, &ids); err != nil {
		return nil, fmt.Errorf("nix eval %s: decoding identities: %w", attr, err)
	}
	return ids, nil
}

// NewRemediationGenerateFloorCmd builds `clearcutt remediation generate-crypto-allowlist`
// (alias generate-floor).
func NewRemediationGenerateFloorCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:     "generate-crypto-allowlist",
		Aliases: []string{"generate-floor"},
		Short:   "Generate the known-good crypto identity allowlist (runtime-patch completeness gate)",
		Long: `Resolves the store-path identities of the CVE-remediated crypto (openssl/sqlite)
across every shipped crypto set by evaluating the flake's cryptoIdentities output
(pure eval, no build), stamps each with provenance (pin + locked rev + output +
version), and writes core/tests/runtime-dep-floor.json.

The gate (closure-cve-check.py and its Go port) default-denies any shipped
openssl/sqlite whose identity is absent from this allowlist — provenance, not
version.

Use --check in CI to fail when the committed allowlist has drifted from what the
flake now resolves (a crypto rebuild without a regenerate, or vice versa).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			resolver := newNixEvalResolver(runtimeFloorOpts.flakeDir)
			return runRemediationGenerateFloor(resolver)
		},
	}
	cmd.Flags().StringVar(&runtimeFloorOpts.flakeDir, "flake-dir", runtimeFloorDefaultFlakeDir, "Flake directory exposing the cryptoIdentities output")
	cmd.Flags().StringVar(&runtimeFloorOpts.out, "out", runtimeFloorDefaultOut, "Path to write the generated allowlist JSON")
	cmd.Flags().StringVar(&runtimeFloorOpts.systems, "systems", runtimeFloorDefaultSystems, "Comma-separated systems to resolve identities for")
	cmd.Flags().StringVar(&runtimeFloorOpts.policyJSON, "policy-json", os.Getenv("REMEDIATION_POLICY_JSON"), "Effective remediation policy JSON from clearcutt.fleet.yaml (selects cryptoTrust)")
	cmd.Flags().BoolVar(&runtimeFloorOpts.check, "check", false, "Verify the committed allowlist matches the flake-resolved identities; non-zero exit on drift")
	return cmd
}

func runRemediationGenerateFloor(resolver cryptoIdentityResolver) error {
	policy := remediationPolicyFromJSON(runtimeFloorOpts.policyJSON)
	systems := splitCommaList(runtimeFloorOpts.systems)
	if len(systems) == 0 {
		return fmt.Errorf("at least one --systems value is required")
	}

	allowlist, err := generateCryptoAllowlist(resolver, systems, policy)
	if err != nil {
		return err
	}

	if runtimeFloorOpts.check {
		return checkCryptoAllowlistInSync(runtimeFloorOpts.out, allowlist)
	}

	if err := writeCryptoAllowlistFile(runtimeFloorOpts.out, allowlist); err != nil {
		return err
	}
	if !GlobalOpts.Quiet {
		summary := make([]string, 0, len(allowlist.Deps))
		for _, d := range allowlist.Deps {
			summary = append(summary, fmt.Sprintf("%s (%d known-good)", d.Name, len(d.KnownGood)))
		}
		fmt.Fprintf(out, "[allowlist] wrote %s: trust=%s, %s.\n",
			runtimeFloorOpts.out, allowlist.Trust, strings.Join(summary, ", "))
	}
	return nil
}

// generateCryptoAllowlist resolves identities for every system, groups them by
// dep, dedups by store path, and assembles the allowlist. Pure aside from the
// injected resolver, so the command and its tests share one code path.
func generateCryptoAllowlist(resolver cryptoIdentityResolver, systems []string, policy fleet.RemediationPolicy) (*CryptoAllowlistFile, error) {
	policy = fleet.EffectiveRemediationPolicy(policy)

	type depAccum struct {
		cve   string
		pins  map[string]bool
		byKey map[string]CryptoKnownGood // dedup by storePath
	}
	deps := map[string]*depAccum{}
	order := []string{}

	for _, system := range systems {
		ids, err := resolver.Resolve(system)
		if err != nil {
			return nil, err
		}
		if len(ids) == 0 {
			return nil, fmt.Errorf("no crypto identities resolved for system %q; refusing to write a vacuous allowlist (the gate would fail open)", system)
		}
		for _, id := range ids {
			name := strings.TrimSpace(id.Name)
			store := strings.TrimSpace(id.StorePath)
			if name == "" || store == "" {
				return nil, fmt.Errorf("resolved a crypto identity with an empty name/storePath for system %q", system)
			}
			acc := deps[name]
			if acc == nil {
				acc = &depAccum{cve: strings.TrimSpace(id.CVE), pins: map[string]bool{}, byKey: map[string]CryptoKnownGood{}}
				deps[name] = acc
				order = append(order, name)
			}
			if acc.cve == "" {
				acc.cve = strings.TrimSpace(id.CVE)
			}
			acc.pins[id.Pin] = true
			acc.byKey[store] = CryptoKnownGood{
				StorePath: store,
				System:    id.System,
				Output:    id.Output,
				Version:   id.Version,
				Pin:       id.Pin,
				Rev:       id.Rev,
			}
		}
	}

	if len(deps) == 0 {
		return nil, fmt.Errorf("policy resolved no crypto-tracked deps; refusing to write a vacuous allowlist (the gate would fail open)")
	}

	sort.Strings(order)
	allowlistDeps := make([]CryptoAllowlistDep, 0, len(order))
	for _, name := range order {
		acc := deps[name]
		known := make([]CryptoKnownGood, 0, len(acc.byKey))
		for _, kg := range acc.byKey {
			known = append(known, kg)
		}
		sort.Slice(known, func(i, j int) bool {
			if known[i].System != known[j].System {
				return known[i].System < known[j].System
			}
			if known[i].Output != known[j].Output {
				return known[i].Output < known[j].Output
			}
			return known[i].StorePath < known[j].StorePath
		})
		pins := make([]string, 0, len(acc.pins))
		for p := range acc.pins {
			pins = append(pins, p)
		}
		sort.Strings(pins)
		allowlistDeps = append(allowlistDeps, CryptoAllowlistDep{
			Name:       name,
			CVE:        acc.cve,
			Provenance: fmt.Sprintf("patched build substituted from %s; identity-vetted (not version-bumped to clear a scanner floor)", strings.Join(pins, ", ")),
			KnownGood:  known,
		})
	}

	return &CryptoAllowlistFile{
		Comment:       runtimeFloorComment,
		SchemaVersion: runtimeFloorSchemaVersion,
		GeneratedBy:   "clearcutt remediation generate-crypto-allowlist",
		Trust:         strings.ToLower(policy.CryptoTrust),
		Deps:          allowlistDeps,
	}, nil
}

func writeCryptoAllowlistFile(path string, allowlist *CryptoAllowlistFile) error {
	raw, err := json.MarshalIndent(allowlist, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to encode crypto allowlist: %w", err)
	}
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create allowlist output directory %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, append(raw, '\n'), 0o644); err != nil {
		return fmt.Errorf("failed to write crypto allowlist to %s: %w", path, err)
	}
	return nil
}

// checkCryptoAllowlistInSync compares the committed allowlist's known-good
// identity SET (per dep) against the freshly-resolved set and fails on drift.
func checkCryptoAllowlistInSync(path string, want *CryptoAllowlistFile) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read committed allowlist %s: %w (run `clearcutt remediation generate-crypto-allowlist`)", path, err)
	}
	var have CryptoAllowlistFile
	if err := json.Unmarshal(raw, &have); err != nil {
		return fmt.Errorf("failed to parse committed allowlist %s: %w", path, err)
	}
	drift := cryptoAllowlistDrift(have.Deps, want.Deps)
	if drift != "" {
		return fmt.Errorf("runtime-dep-floor.json is out of sync with the flake-resolved crypto identities:\n%s\nrun `clearcutt remediation generate-crypto-allowlist` and commit the result", drift)
	}
	if !GlobalOpts.Quiet {
		fmt.Fprintf(out, "[allowlist] in sync: %d crypto dep(s) identity-vetted.\n", len(want.Deps))
	}
	return nil
}

// cryptoAllowlistDrift reports added/removed known-good identities per dep so a
// crypto rebuild without a regenerate (or vice versa) surfaces in the diff.
func cryptoAllowlistDrift(have, want []CryptoAllowlistDep) string {
	indexStores := func(deps []CryptoAllowlistDep) map[string]map[string]bool {
		m := map[string]map[string]bool{}
		for _, d := range deps {
			set := map[string]bool{}
			for _, kg := range d.KnownGood {
				set[kg.StorePath] = true
			}
			m[d.Name] = set
		}
		return m
	}
	h, w := indexStores(have), indexStores(want)
	lines := []string{}
	for name, wset := range w {
		hset, ok := h[name]
		if !ok {
			lines = append(lines, fmt.Sprintf("  + %s: dep newly tracked (%d known-good); missing from committed", name, len(wset)))
			continue
		}
		for store := range wset {
			if !hset[store] {
				lines = append(lines, fmt.Sprintf("  + %s: %s (resolved, missing from committed)", name, store))
			}
		}
		for store := range hset {
			if !wset[store] {
				lines = append(lines, fmt.Sprintf("  - %s: %s (committed, no longer resolved)", name, store))
			}
		}
	}
	for name := range h {
		if _, ok := w[name]; !ok {
			lines = append(lines, fmt.Sprintf("  - %s: dep no longer tracked (committed, not resolved)", name))
		}
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}

// flakeRef turns a bare relative directory (e.g. "core") into a path-form flake
// reference ("./core") so `nix eval` treats it as a local flake rather than a
// registry name. An explicit scheme (path:, git+…), an absolute path, or an
// already-relative "./…" is passed through unchanged.
func flakeRef(dir string) string {
	if dir == "" {
		return "."
	}
	if strings.Contains(dir, ":") || strings.HasPrefix(dir, "/") || strings.HasPrefix(dir, "./") || strings.HasPrefix(dir, "../") || dir == "." {
		return dir
	}
	return "./" + dir
}

func splitCommaList(raw string) []string {
	out := []string{}
	for _, part := range strings.Split(raw, ",") {
		if s := strings.TrimSpace(part); s != "" {
			out = append(out, s)
		}
	}
	return out
}
