package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/northcutted/clearcutt/internal/fleet"
	"github.com/spf13/cobra"
)

// The runtime-patch completeness floor (core/tests/runtime-dep-floor.json) is
// the security keystone of runtime-scoped CVE patching: closure-cve-check.py
// default-denies any shipped openssl/sqlite/... store path below the floor. This
// generator makes the floor's MEMBERSHIP policy-derived (design §6 option B):
// a version-bump CVE overlay enters the floor only when its CVE clears the risk
// bar (fleet.Materiality). The gate MECHANISM is never touched — it keeps
// reading deps[] and proving the floored set shipped. The policy decides what is
// floored; the gate proves the floored set is satisfied; the gate never reads
// EPSS/severity itself.
//
// Guardrails (design Decision 1): kev:always is non-loosenable (a KEV crypto CVE
// is always floored), the effective membership + every policy acceptance is
// recorded as evidence in the file, and the generator refuses to emit an empty
// floor (which would make the default-deny gate vacuous / fail closed).

const runtimeFloorDefaultOverlaysDir = "core/overlays/cve"
const runtimeFloorDefaultOut = "core/tests/runtime-dep-floor.json"

const runtimeFloorComment = "Runtime-patch completeness floor: minimum acceptable versions for CVE-remediated deps that ship inside a production image closure. GENERATED by `clearcutt remediation generate-floor` — do not hand-edit; bump the fixedVersion in the matching core/overlays/cve/*.evidence.json and regenerate. Membership is policy-derived (fleet.Materiality over the overlay evidence): a version-bump CVE overlay is floored only when its CVE clears the risk bar; kev:always findings are always floored. closure-cve-check.py reads deps[] unchanged and default-denies any shipped store path below the floor."

type runtimeFloorFlags struct {
	overlaysDir string
	out         string
	policyJSON  string
	check       bool
}

var runtimeFloorOpts runtimeFloorFlags

// RuntimeFloorDep is one gate-consumed floor entry. The {name, minVersion} shape
// is exactly what closure-cve-check.py load_floor parses; the cve/reason sibling
// keys are recorded evidence (which CVE floored it, and on what basis —
// "severity"/"kev"/"epss" vs "conservative_default" for evidence not yet
// enriched) and are ignored by the gate.
type RuntimeFloorDep struct {
	Name       string `json:"name"`
	MinVersion string `json:"minVersion"`
	CVE        string `json:"cve,omitempty"`
	Reason     string `json:"reason,omitempty"`
}

// RuntimeFloorAcceptance records a version-bump overlay the policy DROPPED from
// the floor (below the risk bar) — evidence that the membership decision was
// taken consciously, not silently. This is the visible-drift guardrail.
type RuntimeFloorAcceptance struct {
	Name         string `json:"name"`
	CVE          string `json:"cve"`
	FixedVersion string `json:"fixedVersion"`
	Disposition  string `json:"disposition"`
	Reason       string `json:"reason"`
}

type runtimeFloorPolicySummary struct {
	Reachability    string  `json:"reachability"`
	MinimumSeverity string  `json:"minimumSeverity"`
	EPSSPercentile  float64 `json:"epssPercentile"`
	KEV             string  `json:"kev"`
}

// RuntimeFloor is the generated floor file. Only deps[] is read by the gate; the
// comment/generatedBy/policy/accepted keys are recorded evidence.
type RuntimeFloor struct {
	Comment     string                    `json:"comment"`
	GeneratedBy string                    `json:"generatedBy"`
	Policy      runtimeFloorPolicySummary `json:"policy"`
	Deps        []RuntimeFloorDep         `json:"deps"`
	Accepted    []RuntimeFloorAcceptance  `json:"accepted,omitempty"`
}

// cveEvidenceFile is the subset of core/overlays/cve/*.evidence.json the floor
// generator reads. The evidence file is the authoritative record of what we
// patch and to what version — a deterministic input, unlike a live scan whose
// closure already ships the patched version.
type cveEvidenceFile struct {
	CVE             string                       `json:"cve"`
	Package         string                       `json:"package"`
	Status          string                       `json:"status"`
	RiskFactors     cveEvidenceRiskFactors       `json:"riskFactors"`
	ExpectedRemoved []cveEvidenceExpectedRemoved `json:"expectedRemoved"`
}

type cveEvidenceRiskFactors struct {
	KnownExploited bool     `json:"knownExploited"`
	Severity       string   `json:"severity,omitempty"`
	EPSSPercentile *float64 `json:"epssPercentile,omitempty"`
}

type cveEvidenceExpectedRemoved struct {
	CVE              string `json:"cve"`
	Package          string `json:"package"`
	InstalledVersion string `json:"installedVersion"`
	FixedVersion     string `json:"fixedVersion,omitempty"`
}

// NewRemediationGenerateFloorCmd builds `clearcutt remediation generate-floor`.
func NewRemediationGenerateFloorCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate-floor",
		Short: "Generate the policy-derived runtime-patch completeness floor",
		Long: `Derives core/tests/runtime-dep-floor.json from the CVE overlay evidence and the
risk policy: a version-bump CVE overlay is floored only when its CVE clears the
materiality bar (fleet.Materiality). The closure-cve-check.py gate is never
modified — it keeps default-denying over whatever deps[] the policy produced.

Use --check in CI to fail when the committed floor has drifted from what the
policy + evidence would generate.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runRemediationGenerateFloor()
		},
	}
	cmd.Flags().StringVar(&runtimeFloorOpts.overlaysDir, "overlays-dir", runtimeFloorDefaultOverlaysDir, "Directory of CVE overlay evidence (*.evidence.json)")
	cmd.Flags().StringVar(&runtimeFloorOpts.out, "out", runtimeFloorDefaultOut, "Path to write the generated floor JSON")
	cmd.Flags().StringVar(&runtimeFloorOpts.policyJSON, "policy-json", os.Getenv("REMEDIATION_POLICY_JSON"), "Effective remediation policy JSON from clearcutt.fleet.yaml")
	cmd.Flags().BoolVar(&runtimeFloorOpts.check, "check", false, "Verify the committed floor matches the policy-derived floor; non-zero exit on drift")
	return cmd
}

func runRemediationGenerateFloor() error {
	policy := remediationPolicyFromJSON(runtimeFloorOpts.policyJSON)
	floor, warnings, err := generateRuntimeFloor(runtimeFloorOpts.overlaysDir, policy)
	if err != nil {
		return err
	}
	for _, w := range warnings {
		logRemediationRun("floor: %s", w)
	}

	if runtimeFloorOpts.check {
		return checkRuntimeFloorInSync(runtimeFloorOpts.out, floor)
	}

	if err := writeRuntimeFloorFile(runtimeFloorOpts.out, floor); err != nil {
		return err
	}
	if !GlobalOpts.Quiet {
		tracked := make([]string, 0, len(floor.Deps))
		for _, d := range floor.Deps {
			tracked = append(tracked, fmt.Sprintf("%s>=%s", d.Name, d.MinVersion))
		}
		fmt.Fprintf(out, "[floor] wrote %s: %d dep(s) floored (%s), %d policy-accepted.\n",
			runtimeFloorOpts.out, len(floor.Deps), strings.Join(tracked, ", "), len(floor.Accepted))
	}
	return nil
}

// generateRuntimeFloor applies the risk policy to the CVE overlay evidence and
// returns the policy-derived floor. It is pure (filesystem read only) and the
// single decision point, so the command and its tests share one code path.
func generateRuntimeFloor(overlaysDir string, policy fleet.RemediationPolicy) (*RuntimeFloor, []string, error) {
	policy = fleet.EffectiveRemediationPolicy(policy)

	pattern := filepath.Join(overlaysDir, "*.evidence.json")
	files, err := filepath.Glob(pattern)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to list CVE overlay evidence: %w", err)
	}
	sort.Strings(files)

	type flooredDep struct {
		minVersion string
		cve        string
		reason     string
	}
	floored := map[string]*flooredDep{}
	accepted := []RuntimeFloorAcceptance{}
	warnings := []string{}

	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			return nil, nil, fmt.Errorf("failed to read overlay evidence %s: %w", file, err)
		}
		var ev cveEvidenceFile
		if err := json.Unmarshal(raw, &ev); err != nil {
			return nil, nil, fmt.Errorf("failed to parse overlay evidence %s: %w", file, err)
		}
		dep := strings.TrimSpace(ev.Package)
		if dep == "" {
			continue
		}

		decision, warning := floorDecisionForEvidence(ev, policy)

		// Floor candidate = the highest clean dotted-numeric fixedVersion across
		// the removed CVEs. Overlays with no version-bump fix (fetchpatch patches
		// that keep the version, e.g. the CPython branch patch) are not
		// version-floorable and are skipped — the gate proves a floor by version.
		fixedVersion := ""
		sawMalformedFix := false
		for _, er := range ev.ExpectedRemoved {
			v := strings.TrimSpace(er.FixedVersion)
			if v == "" {
				continue
			}
			if !isCleanDottedNumeric(v) {
				sawMalformedFix = true
				continue
			}
			if fixedVersion == "" || compareVersionLike(v, fixedVersion) > 0 {
				fixedVersion = v
			}
		}
		if fixedVersion == "" {
			// A must_fix overlay whose only fix versions are malformed must NOT
			// silently vanish from the gate (the silent-loss failure class) —
			// fail closed so the evidence author supplies a clean version string.
			// A patch-only overlay (no fixedVersion at all) is legitimately not
			// version-floorable and is skipped quietly.
			if sawMalformedFix && decision.Disposition == fleet.DispositionMustFix {
				return nil, warnings, fmt.Errorf(
					"overlay evidence for %s (%s) is must_fix but no expectedRemoved.fixedVersion is a clean dotted-numeric version; "+
						"refusing to silently drop it from the floor — fix the fixedVersion string",
					dep, ev.CVE)
			}
			if sawMalformedFix {
				warnings = append(warnings, fmt.Sprintf("%s (%s): expectedRemoved.fixedVersion is malformed and not floorable; skipped", dep, ev.CVE))
			}
			continue
		}
		if warning != "" {
			warnings = append(warnings, warning)
		}

		if decision.Disposition == fleet.DispositionMustFix {
			existing, ok := floored[dep]
			if !ok || compareVersionLike(fixedVersion, existing.minVersion) > 0 {
				floored[dep] = &flooredDep{minVersion: fixedVersion, cve: ev.CVE, reason: decision.Reason}
			}
			continue
		}
		accepted = append(accepted, RuntimeFloorAcceptance{
			Name:         dep,
			CVE:          ev.CVE,
			FixedVersion: fixedVersion,
			Disposition:  string(decision.Disposition),
			Reason:       decision.Reason,
		})
	}

	if len(floored) == 0 {
		return nil, warnings, fmt.Errorf(
			"policy-derived floor is empty: no version-bump CVE overlay in %s cleared the risk bar. "+
				"A vacuous floor makes the runtime-cve gate fail closed; refusing to write. "+
				"Check the policy thresholds or the overlay evidence",
			overlaysDir)
	}

	names := make([]string, 0, len(floored))
	for name := range floored {
		names = append(names, name)
	}
	sort.Strings(names)
	deps := make([]RuntimeFloorDep, 0, len(names))
	for _, name := range names {
		deps = append(deps, RuntimeFloorDep{
			Name:       name,
			MinVersion: floored[name].minVersion,
			CVE:        floored[name].cve,
			Reason:     floored[name].reason,
		})
	}
	sort.Slice(accepted, func(i, j int) bool {
		if accepted[i].Name != accepted[j].Name {
			return accepted[i].Name < accepted[j].Name
		}
		return accepted[i].CVE < accepted[j].CVE
	})

	floor := &RuntimeFloor{
		Comment:     runtimeFloorComment,
		GeneratedBy: "clearcutt remediation generate-floor",
		Policy: runtimeFloorPolicySummary{
			Reachability:    policy.Reachability,
			MinimumSeverity: policy.MinimumSeverity,
			EPSSPercentile:  policy.EPSSPercentile,
			KEV:             policy.KEV,
		},
		Deps:     deps,
		Accepted: accepted,
	}
	return floor, warnings, nil
}

// floorDecisionForEvidence runs the risk policy over one overlay's evidence. A
// version-bump crypto patch with no structured severity/EPSS/KEV cannot be
// gated, so it is floored conservatively (fail-closed) and flagged — the policy
// never silently drops a real fix it lacks the data to evaluate.
func floorDecisionForEvidence(ev cveEvidenceFile, policy fleet.RemediationPolicy) (fleet.RiskDecision, string) {
	gated := strings.TrimSpace(ev.RiskFactors.Severity) != "" ||
		ev.RiskFactors.EPSSPercentile != nil ||
		ev.RiskFactors.KnownExploited
	if !gated {
		return fleet.RiskDecision{Disposition: fleet.DispositionMustFix, Reason: "conservative_default"},
			fmt.Sprintf("%s (%s) carries no structured severity/EPSS/KEV; flooring conservatively until the evidence is enriched", ev.Package, ev.CVE)
	}
	decision := fleet.Materiality(fleet.MaterialityInput{
		Severity:       ev.RiskFactors.Severity,
		EPSSPercentile: ev.RiskFactors.EPSSPercentile,
		KEV:            ev.RiskFactors.KnownExploited,
		Layer:          "runtime", // floored deps ship in the runtime closure by construction
		HasFix:         true,      // a version-bump fixedVersion exists
		ProductionTier: true,      // the floor governs production image closures
	}, policy)
	return decision, ""
}

func writeRuntimeFloorFile(path string, floor *RuntimeFloor) error {
	raw, err := json.MarshalIndent(floor, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to encode runtime floor: %w", err)
	}
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create floor output directory %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, append(raw, '\n'), 0o644); err != nil {
		return fmt.Errorf("failed to write runtime floor to %s: %w", path, err)
	}
	return nil
}

// checkRuntimeFloorInSync compares the committed floor's deps[] (the only
// gate-relevant content) against the policy-derived floor and fails on drift.
func checkRuntimeFloorInSync(path string, want *RuntimeFloor) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read committed floor %s: %w (run `clearcutt remediation generate-floor`)", path, err)
	}
	var have RuntimeFloor
	if err := json.Unmarshal(raw, &have); err != nil {
		return fmt.Errorf("failed to parse committed floor %s: %w", path, err)
	}
	// Compare BOTH the floored set and the policy-accepted (dropped) set. A
	// policy change that moves a crypto dep deps[] -> accepted[] is a legitimate
	// option-B membership change, but it must not pass --check silently: forcing
	// a regenerate+commit makes the drop appear in the reviewed diff (the audit
	// guardrail the absolute claim traded away).
	drift := runtimeFloorDepDrift(have.Deps, want.Deps)
	if accDrift := runtimeFloorAcceptedDrift(have.Accepted, want.Accepted); accDrift != "" {
		if drift != "" {
			drift += "\n"
		}
		drift += accDrift
	}
	if drift != "" {
		return fmt.Errorf("runtime-dep-floor.json is out of sync with the policy-derived floor:\n%s\nrun `clearcutt remediation generate-floor` and commit the result", drift)
	}
	if !GlobalOpts.Quiet {
		fmt.Fprintf(out, "[floor] in sync: %d dep(s) floored, %d policy-accepted.\n", len(want.Deps), len(want.Accepted))
	}
	return nil
}

// runtimeFloorAcceptedDrift reports differences in the policy-accepted (dropped)
// set, keyed by name+CVE, so a crypto dep newly dropped from the floor surfaces
// as drift until the regeneration is committed.
func runtimeFloorAcceptedDrift(have, want []RuntimeFloorAcceptance) string {
	index := func(items []RuntimeFloorAcceptance) map[string]string {
		m := map[string]string{}
		for _, a := range items {
			m[a.Name+"\x00"+a.CVE] = a.Reason
		}
		return m
	}
	h, w := index(have), index(want)
	lines := []string{}
	for key, wr := range w {
		name := strings.SplitN(key, "\x00", 2)[0]
		if _, ok := h[key]; !ok {
			lines = append(lines, fmt.Sprintf("  + accepted %s (policy now drops it from the floor: %s); regenerate to record it", name, wr))
		}
	}
	for key := range h {
		name := strings.SplitN(key, "\x00", 2)[0]
		if _, ok := w[key]; !ok {
			lines = append(lines, fmt.Sprintf("  - accepted %s (committed as dropped, but policy now floors it again)", name))
		}
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}

func runtimeFloorDepDrift(have, want []RuntimeFloorDep) string {
	index := func(deps []RuntimeFloorDep) map[string]string {
		m := map[string]string{}
		for _, d := range deps {
			m[d.Name] = d.MinVersion
		}
		return m
	}
	h, w := index(have), index(want)
	lines := []string{}
	for name, wv := range w {
		if hv, ok := h[name]; !ok {
			lines = append(lines, fmt.Sprintf("  + %s>=%s (policy floors it; missing from committed)", name, wv))
		} else if hv != wv {
			lines = append(lines, fmt.Sprintf("  ~ %s: committed %s, policy %s", name, hv, wv))
		}
	}
	for name, hv := range h {
		if _, ok := w[name]; !ok {
			lines = append(lines, fmt.Sprintf("  - %s>=%s (committed, but policy no longer floors it)", name, hv))
		}
	}
	sort.Strings(lines)
	return strings.Join(lines, "\n")
}

// isCleanDottedNumeric mirrors closure-cve-check.py parse_version: only purely
// numeric dotted segments are a floorable version, so the generated minVersion
// never trips the gate's own fail-closed parser.
func isCleanDottedNumeric(v string) bool {
	if v == "" {
		return false
	}
	for _, part := range strings.Split(v, ".") {
		if part == "" {
			return false
		}
		for _, r := range part {
			if r < '0' || r > '9' {
				return false
			}
		}
	}
	return true
}
