package commands

import (
	"fmt"
	"strings"

	"github.com/northcutted/clearcutt/internal/certify"
	"github.com/spf13/cobra"
)

type runtimeCveFlags struct {
	floor      string
	storePaths string
}

var runtimeCveOpts runtimeCveFlags

// newVerifyRuntimeCveCmd is the native-Go port of
// core/tests/closure-cve-check.py: it default-denies any shipped openssl/sqlite
// store path whose IDENTITY is not on the committed known-good allowlist. Exit
// code follows the CLI contract: 0 clean, 2 on violations, 1 on operational error.
func newVerifyRuntimeCveCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "runtime-cve [image-archive]",
		Short: "Gate the shipped closure: every CVE-remediated crypto path is a known-good identity",
		Long: `Runtime-patch completeness gate: proves no UNKNOWN build of a CVE-remediated
crypto dependency (openssl/sqlite) ships inside a production image. Walks the
SHIPPED closure — a docker-save or OCI-layout image archive, or a closureInfo
store-paths file via --store-paths — and fails (default-deny) on any
openssl/sqlite store path whose IDENTITY is absent from the committed known-good
allowlist (provenance, not version: a patched-not-bumped openssl passes by
identity; an unvetted higher version fails).

The allowlist (--floor, required) is the source of truth, generated by
'clearcutt remediation generate-crypto-allowlist' into
core/tests/runtime-dep-floor.json.

This is the native-Go port of core/tests/closure-cve-check.py.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			archive := ""
			if len(args) == 1 {
				archive = args[0]
			}
			return runVerifyRuntimeCve(archive)
		},
	}
	cmd.Flags().StringVar(&runtimeCveOpts.floor, "floor", "", "runtime-dep-floor.json: the known-good crypto identity allowlist (required, source of truth)")
	cmd.Flags().StringVar(&runtimeCveOpts.storePaths, "store-paths", "", "closureInfo store-paths file to scan instead of an image archive")
	_ = cmd.MarkFlagRequired("floor")
	return cmd
}

func runVerifyRuntimeCve(archive string) error {
	if (archive != "") == (runtimeCveOpts.storePaths != "") {
		return fmt.Errorf("provide exactly one of <image-archive> or --store-paths FILE")
	}

	floor, err := certify.LoadRuntimeDepFloor(runtimeCveOpts.floor)
	if err != nil {
		return err
	}

	var result certify.RuntimeCveResult
	if archive != "" {
		result, err = certify.ScanImageArchiveForRuntimeCve(archive, floor)
	} else {
		result, err = certify.ScanStorePathsForRuntimeCve(runtimeCveOpts.storePaths, floor)
	}
	if err != nil {
		return err
	}

	if !result.Clean() {
		for _, v := range result.Violations {
			fmt.Fprintf(errOut, "[runtime-cve] VIOLATION: %s\n", v.Message)
		}
		fmt.Fprintf(errOut, "[runtime-cve] %d violation(s). The shipped closure carries an off-allowlist build of a CVE-remediated crypto dependency. Source the runtime from the provenance-allowlisted openssl/sqlite, or — if this is a new known-good build — regenerate the allowlist with `clearcutt remediation generate-crypto-allowlist` and commit it.\n", len(result.Violations))
		return ErrCheckFailed
	}

	fmt.Fprintf(out, "[runtime-cve] clean: every shipped crypto path matches a known-good identity (%s).\n", strings.Join(result.Tracked, ", "))
	return nil
}
