package commands

import (
	"fmt"
	"strings"

	"github.com/northcutted/clearcutt/internal/certify"
	"github.com/spf13/cobra"
)

type runtimeCveFlags struct {
	floor      string
	storePaths string
}

var runtimeCveOpts runtimeCveFlags

// newVerifyRuntimeCveCmd is the native-Go port of
// core/tests/closure-cve-check.py: it default-denies any shipped openssl/sqlite
// store path below the committed floor. Exit code follows the CLI contract: 0
// clean, 2 on violations, 1 on operational error.
func newVerifyRuntimeCveCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "runtime-cve [image-archive]",
		Short: "Gate the shipped closure: no stock (below-floor) build of a CVE-remediated dep",
		Long: `Runtime-patch completeness gate: proves no STOCK (unpatched) build of a
CVE-remediated dependency ships inside a production image. Walks the SHIPPED
closure — a docker-save or OCI-layout image archive, or a closureInfo
store-paths file via --store-paths — and fails (default-deny) on any
openssl/sqlite store path whose version is below the committed floor.

The floor (--floor, required) is the source of truth, generated by
'clearcutt remediation generate-floor' into core/tests/runtime-dep-floor.json.

This is the native-Go port of core/tests/closure-cve-check.py.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			archive := ""
			if len(args) == 1 {
				archive = args[0]
			}
			return runVerifyRuntimeCve(archive)
		},
	}
	cmd.Flags().StringVar(&runtimeCveOpts.floor, "floor", "", "runtime-dep-floor.json: the version floor (required, source of truth)")
	cmd.Flags().StringVar(&runtimeCveOpts.storePaths, "store-paths", "", "closureInfo store-paths file to scan instead of an image archive")
	_ = cmd.MarkFlagRequired("floor")
	return cmd
}

func runVerifyRuntimeCve(archive string) error {
	if (archive != "") == (runtimeCveOpts.storePaths != "") {
		return fmt.Errorf("provide exactly one of <image-archive> or --store-paths FILE")
	}

	floor, err := certify.LoadRuntimeDepFloor(runtimeCveOpts.floor)
	if err != nil {
		return err
	}

	var result certify.RuntimeCveResult
	if archive != "" {
		result, err = certify.ScanImageArchiveForRuntimeCve(archive, floor)
	} else {
		result, err = certify.ScanStorePathsForRuntimeCve(runtimeCveOpts.storePaths, floor)
	}
	if err != nil {
		return err
	}

	if !result.Clean() {
		for _, v := range result.Violations {
			fmt.Fprintf(errOut, "[runtime-cve] VIOLATION: %s\n", v.Message)
		}
		fmt.Fprintf(errOut, "[runtime-cve] %d violation(s). The shipped closure carries an unpatched build of a CVE-remediated dependency. Patch the offending runtime (override its openssl/sqlite input) or raise the floor in core/tests/runtime-dep-floor.json with evidence.\n", len(result.Violations))
		return ErrCheckFailed
	}

	fmt.Fprintf(out, "[runtime-cve] clean: every shipped dep meets the floor (%s).\n", strings.Join(result.Tracked, ", "))
	return nil
}
