# ClearCutt Hardened Fleets Declarative Entrypoint

{
  description = "ClearCutt Hardened Base Image Fleets - Declarative, CVE-aware Nix Store Layers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      linuxSystems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      darwinSystems = [
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      systems = linuxSystems ++ darwinSystems;
      forAllSystems = nixpkgs.lib.genAttrs systems;
      forLinuxSystems = nixpkgs.lib.genAttrs linuxSystems;
      forDarwinSystems = nixpkgs.lib.genAttrs darwinSystems;

      # One nixpkgs configuration for every consumption surface — fleet
      # images, grafted images, brokered shells, and exported overlays must
      # all resolve from the same remediated package set.
      cveRemediationOverlay = import ./overlays/cve-remediation.nix;
      # Build-toolchain fixes for packages the CVE rebinds force from source
      # (e.g. p11-kit's sandbox-flaky test); see overlays/toolchain-ci-fixes.nix.
      toolchainFixesOverlay = import ./overlays/toolchain-ci-fixes.nix;
      nixpkgsConfig = {
        # `allowUnfree` is required for JDKs (Zulu/Oracle) and a few fonts.
        # `allowBroken` was removed: it let Nix produce binaries from
        # packages maintainers had flagged broken, which is incompatible
        # with the project's fixable-CVE gate. If a specific package is
        # incorrectly marked broken, override it inside overlays/cve/.
        allowUnfree = true;
      };
      importRemediatedNixpkgs = system: import nixpkgs {
        inherit system;
        config = nixpkgsConfig;
        overlays = [ cveRemediationOverlay toolchainFixesOverlay ];
      };

      perSystem = system:
      let
        hostPkgs = importRemediatedNixpkgs system;

        # Host package alignment: build native OCI layers on Linux release
        # runners, and expose native development shells on Darwin for the local
        # inner loop instead of relying on pkgsCross for image builds.
        pkgs = hostPkgs;

        # Import centralized language and runtime registry once per system
        # and thread it into the compiler and native helpers, which would
        # otherwise each re-instantiate it against the same pkgs.
        registry = import ./lib/registry.nix { inherit pkgs; };

        # Import our custom image compiler
        compiler = import ./lib/build-fleet.nix { inherit pkgs registry; };

        # Configured first-class service image specs generated by
        # `clearcutt service scaffold` from clearcutt.fleet.yaml.
        serviceSpecs = import ./lib/service-extensions.nix {};

        # Fork-configurable output identity generated from clearcutt.fleet.yaml.
        platformMetadata = import ./lib/platform-metadata.nix;
        imagePrefix = platformMetadata.imagePrefix or "clearcutt";
        productName = platformMetadata.productName or "ClearCutt";

        # Helper to generate standard package name attributes
        mkPackageName = lang: ver: tier: "${lang}${ver}-${tier}";

        # Matrix specifications - dynamically generated from the central registry
        languages = builtins.filter (lang: lang != "dotnet-runtime") (builtins.attrNames registry.languages);
        versions = builtins.mapAttrs (lang: spec: builtins.attrNames spec.versions) registry.languages;
        tiers = [ "dev" "slim" "distroless" ];

        # Generate image package outputs for the Linux build systems only.
        # Darwin still exposes native runtime closures and dev shells, but not
        # OCI image attrs that require Linux container tooling.
        matrixPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.concatMap (ver:
              pkgs.lib.map (tier:
                let
                  attrName = mkPackageName lang ver tier;
                in
                {
                  name = attrName;
                  value = compiler.buildFleetImage {
                    name = "${imagePrefix}-${lang}-${ver}";
                    tag = tier;
                    language = lang;
                    version = ver;
                    inherit tier;
                  };
                }
              ) tiers
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

        servicePackages = pkgs.lib.listToAttrs (
          builtins.map (service: {
            name = service.id;
            value = compiler.buildServiceImage {
              name = "${imagePrefix}-${service.id}";
              tag = "current";
              inherit service;
            };
          }) serviceSpecs
        );

        # Resolve raw, dynamic-link-patched matrix runtimes
        nativeHelpers = import ./lib/nix-native.nix { inherit self registry; pkgs = hostPkgs; };

        # Generate a set of raw, dynamic-link-patched matrix runtimes
        # e.g., packages.x86_64-linux.nodejs22-native
        rawPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver:
              let
                attrName = "${lang}${ver}-native";
              in
              {
                name = attrName;
                # Get the first package in the list returned by resolveRawPackages
                value = pkgs.lib.head (nativeHelpers.resolveRawPackages { language = lang; version = ver; });
              }
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) (pkgs.lib.filter (x: x != "core") languages)
        );

        # Per-target hardened dev shells mirror each dev image's runtime closure,
        # so `nix develop .#java21-dev` drops you into the same toolchain the
        # java21:dev image ships. Built natively per host (incl. Darwin) for the
        # local inner loop — this is what `clearcutt dev --nix` resolves to.
        devTargetShells = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver: {
              name = "${lang}${ver}-dev";
              value = nativeHelpers.mkHardenedShell { language = lang; version = ver; };
            }) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

      in
      {
        imagePackages = matrixPackages // servicePackages;
        nativePackages = rawPackages;

        # Default dev shell (build/gating tooling) plus per-target dev shells
        # (devTargetShells) for the local inner loop.
        devShells = {
          default = hostPkgs.mkShell {
          name = "${imagePrefix}-dev-shell";

          # System tools required for local builds, scanning, and inspection,
          # plus the contributor toolchains for the Go CLI and the Astro site.
          buildInputs = [
            hostPkgs.git
            hostPkgs.curl
            hostPkgs.patchelf
            hostPkgs.cosign
            hostPkgs.trivy
            hostPkgs.grype
            hostPkgs.syft
            hostPkgs.skopeo
            hostPkgs.container-structure-test
            hostPkgs.go
            hostPkgs.gopls
            hostPkgs.nodejs
          ];

          shellHook = ''
            if [ -f ${./lib/credential-broker.sh} ]; then
              source ${./lib/credential-broker.sh}
              install_credential_broker_trap
            fi
          '';
          };
        } // devTargetShells;
      };
      # Evaluate each system exactly once: packages and devShells previously
      # called perSystem independently, paying for the nixpkgs import and
      # matrix construction twice per system.
      evaluated = forAllSystems perSystem;
    in
    {
      packages =
        (forLinuxSystems (system:
          evaluated.${system}.imagePackages // evaluated.${system}.nativePackages
        ))
        // (forDarwinSystems (system: evaluated.${system}.nativePackages));
      devShells = forAllSystems (system: evaluated.${system}.devShells);

      # The fleet's CVE patch set, exported standalone so downstreams can
      # apply or audit the remediations directly.
      overlays.cveRemediation = cveRemediationOverlay;

      # Raw overlay for downstream consumers. The CVE remediation overlay is
      # composed in first, and the registry attrs resolve against `final`
      # (inside helpers.overlay), so clearcutt* attrs carry the same patched
      # runtimes the fleet images ship.
      overlays.default = nixpkgs.lib.composeManyExtensions [
        cveRemediationOverlay
        toolchainFixesOverlay
        (final: prev:
          let
            helpers = import ./lib/nix-native.nix { inherit self; pkgs = prev; };
          in
          helpers.overlay final prev)
      ];

      # Reusable Library Helper for creating custom brokered shells
      lib = {
        # Registry truth surface: the flat list of runtime line ids the
        # registry actually compiles ("coreLTS", "java21", "python3.13", ...),
        # mirroring the flake's own image-matrix exclusions (dotnet-runtime is
        # a virtual overlay-only line filtered out of `languages` above).
        # Consumed by tests/verify.sh's registry↔fleet drift gate so
        # clearcutt.fleet.yaml `matrix.languages` can never silently diverge
        # from lib/registry.nix again. Listing attr names never forces the
        # package values, so this stays cheap and system-independent.
        runtimeLines =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config.allowUnfree = true;
            };
            registry = import ./lib/registry.nix { inherit pkgs; };
            imageLanguages = builtins.filter (lang: lang != "dotnet-runtime")
              (builtins.attrNames registry.languages);
          in
          nixpkgs.lib.concatMap (lang:
            map (ver: "${lang}${ver}")
              (builtins.attrNames registry.languages.${lang}.versions)
          ) imageLanguages;

        mkHardenedShell = { system, language, version, ... }@args:
          let
            # Brokered shells must resolve from the same remediated, unfree-
            # enabled package set as the fleet images; a bare nixpkgs import
            # here silently handed out unpatched runtimes.
            pkgs = importRemediatedNixpkgs system;
            helpers = import ./lib/nix-native.nix { inherit self pkgs; };
          in
          helpers.mkHardenedShell (pkgs.lib.filterAttrs (n: v: n != "system") args);

        graftOntoBase =
          { system
          , fromImage
          , runtime ? null
          , language ? null
          , version ? null
          , tier ? "distroless"
          , tag ? "grafted"
          , name ? null
          , ...
          }@args:
          let
            pkgs = importRemediatedNixpkgs system;
            compiler = import ./lib/build-fleet.nix { inherit pkgs; };
            platformMetadata = import ./lib/platform-metadata.nix;
            imagePrefix = platformMetadata.imagePrefix or "clearcutt";
            parseRuntime = runtimeId:
              if runtimeId == "coreLTS" then {
                language = "core";
                version = "LTS";
              } else
                let
                  parsed = builtins.match "([A-Za-z]+)([0-9].*)" runtimeId;
                in
                if parsed == null then
                  throw "clearcutt.lib.graftOntoBase: runtime must look like java21, python3.15, go1.25, dotnet8, rust1.95, cc15, or coreLTS"
                else {
                  language = builtins.elemAt parsed 0;
                  version = builtins.elemAt parsed 1;
                };
            parsedRuntime =
              if runtime != null then parseRuntime runtime else {};
            languageFinal =
              if language != null then language
              else parsedRuntime.language or (throw "clearcutt.lib.graftOntoBase requires runtime or language");
            versionFinal =
              if version != null then version
              else parsedRuntime.version or (throw "clearcutt.lib.graftOntoBase requires runtime or version");
            imageName = if name == null then "${imagePrefix}-${languageFinal}-${versionFinal}" else name;
            cleanArgs = pkgs.lib.filterAttrs (n: v: !(builtins.elem n [
              "system"
              "name"
              "runtime"
              "language"
              "version"
              "tag"
              "tier"
              "fromImage"
            ])) args;
          in
          compiler.buildFleetImage (cleanArgs // {
            name = imageName;
            tag = tag;
            language = languageFinal;
            version = versionFinal;
            tier = tier;
            fromImage = fromImage;
          });
      };

      # Closure-purity security gate for `nix flake check`, Linux-only because
      # the OCI image matrix is only exposed for Linux systems. For each
      # representative distroless image, closureInfo materializes the full
      # runtime closure of the image's contents and
      # tests/closure-purity-check.py fails the build if that closure provides
      # interactive shells (bin/sh|bash|ash|dash), package-manager binaries
      # (npm, npx, corepack, pip*, apk, dpkg, rpm), or setuid/setgid files —
      # honoring the same explained-exception allowlist
      # (tests/closure-purity-allowlist.txt) as the verify.sh image gate, so
      # a residual finding is consciously accepted rather than silently
      # weakening the gate. Add coverage by appending to closurePurityTargets.
      checks = forLinuxSystems (system:
        let
          checkPkgs = import nixpkgs { inherit system; };
          closurePurityTargets = [
            "coreLTS-distroless"
            "node22-distroless"
            "java21-distroless"
            "python3.13-distroless"
          ];
          mkClosurePurityCheck = attrName:
            let
              image = self.packages.${system}.${attrName};
              closure = checkPkgs.closureInfo { rootPaths = image.clearcuttContents; };
            in
            checkPkgs.runCommand "closure-purity-${attrName}"
              {
                nativeBuildInputs = [ checkPkgs.python3 ];
              } ''
              python3 ${./tests/closure-purity-check.py} \
                --store-paths ${closure}/store-paths \
                --allowlist ${./tests/closure-purity-allowlist.txt}
              touch $out
            '';
        in
        nixpkgs.lib.genAttrs
          (map (target: "closure-purity-${target}") closurePurityTargets)
          (name: mkClosurePurityCheck (nixpkgs.lib.removePrefix "closure-purity-" name))
      );
    };
}
