# ClearCutt Hardened Fleets Declarative Entrypoint

{
  description = "ClearCutt Hardened Base Image Fleets - Declarative, CVE-aware Nix Store Layers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      linuxSystems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      darwinSystems = [
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      systems = linuxSystems ++ darwinSystems;
      forAllSystems = nixpkgs.lib.genAttrs systems;
      forLinuxSystems = nixpkgs.lib.genAttrs linuxSystems;
      forDarwinSystems = nixpkgs.lib.genAttrs darwinSystems;
      perSystem = system:
      let
        hostPkgs = import nixpkgs {
          inherit system;
          config = {
            # `allowUnfree` is required for JDKs (Zulu/Oracle) and a few fonts.
            # `allowBroken` was removed: it let Nix produce binaries from
            # packages maintainers had flagged broken, which is incompatible
            # with the project's fixable-CVE gate. If a specific package is
            # incorrectly marked broken, override it inside overlays/cve/.
            allowUnfree = true;
          };
          overlays = [
            (import ./overlays/cve-remediation.nix)
          ];
        };

        # Host package alignment: build native OCI layers on Linux release
        # runners, and expose native development shells on Darwin for the local
        # inner loop instead of relying on pkgsCross for image builds.
        pkgs = hostPkgs;

        # Import centralized language and runtime registry
        registry = import ./lib/registry.nix { inherit pkgs; };

        # Import our custom image compiler
        compiler = import ./lib/build-fleet.nix { inherit pkgs; };

        # Configured first-class service image specs generated by
        # `clearcutt service scaffold` from clearcutt.fleet.yaml.
        serviceSpecs = import ./lib/service-extensions.nix {};

        # Fork-configurable output identity generated from clearcutt.fleet.yaml.
        platformMetadata = import ./lib/platform-metadata.nix;
        imagePrefix = platformMetadata.imagePrefix or "clearcutt";
        productName = platformMetadata.productName or "ClearCutt";

        # Helper to generate standard package name attributes
        mkPackageName = lang: ver: tier: "${lang}${ver}-${tier}";

        # Matrix specifications - dynamically generated from the central registry
        languages = builtins.filter (lang: lang != "dotnet-runtime") (builtins.attrNames registry.languages);
        versions = builtins.mapAttrs (lang: spec: builtins.attrNames spec.versions) registry.languages;
        tiers = [ "dev" "slim" "distroless" ];

        # Generate image package outputs for the Linux build systems only.
        # Darwin still exposes native runtime closures and dev shells, but not
        # OCI image attrs that require Linux container tooling.
        matrixPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.concatMap (ver:
              pkgs.lib.map (tier:
                let
                  attrName = mkPackageName lang ver tier;
                in
                {
                  name = attrName;
                  value = compiler.buildFleetImage {
                    name = "${imagePrefix}-${lang}-${ver}";
                    tag = tier;
                    language = lang;
                    version = ver;
                    inherit tier;
                  };
                }
              ) tiers
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

        servicePackages = pkgs.lib.listToAttrs (
          builtins.map (service: {
            name = service.id;
            value = compiler.buildServiceImage {
              name = "${imagePrefix}-${service.id}";
              tag = "current";
              inherit service;
            };
          }) serviceSpecs
        );

        # Resolve raw, dynamic-link-patched matrix runtimes
        nativeHelpers = import ./lib/nix-native.nix { inherit self; pkgs = hostPkgs; };

        # Generate a set of raw, dynamic-link-patched matrix runtimes
        # e.g., packages.x86_64-linux.nodejs22-native
        rawPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver:
              let
                attrName = "${lang}${ver}-native";
              in
              {
                name = attrName;
                # Get the first package in the list returned by resolveRawPackages
                value = pkgs.lib.head (nativeHelpers.resolveRawPackages { language = lang; version = ver; });
              }
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) (pkgs.lib.filter (x: x != "core") languages)
        );

        # Per-target hardened dev shells mirror each dev image's runtime closure,
        # so `nix develop .#java21-dev` drops you into the same toolchain the
        # java21:dev image ships. Built natively per host (incl. Darwin) for the
        # local inner loop — this is what `clearcutt dev --nix` resolves to.
        devTargetShells = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver: {
              name = "${lang}${ver}-dev";
              value = nativeHelpers.mkHardenedShell { language = lang; version = ver; };
            }) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

      in
      {
        imagePackages = matrixPackages // servicePackages;
        nativePackages = rawPackages;

        # Default dev shell (build/gating tooling) plus per-target dev shells
        # (devTargetShells) for the local inner loop.
        devShells = {
          default = hostPkgs.mkShell {
          name = "${imagePrefix}-dev-shell";

          # System tools required for local builds, scanning, and inspection
          buildInputs = [
            hostPkgs.git
            hostPkgs.curl
            hostPkgs.patchelf
            hostPkgs.cosign
            hostPkgs.trivy
            hostPkgs.grype
            hostPkgs.syft
            hostPkgs.skopeo
            hostPkgs.container-structure-test
          ];

          shellHook = ''
            if [ -f ${./lib/credential-broker.sh} ]; then
              source ${./lib/credential-broker.sh}
              install_credential_broker_trap
            fi
          '';
          };
        } // devTargetShells;
      };
    in
    {
      packages =
        (forLinuxSystems (system:
          let p = perSystem system;
          in p.imagePackages // p.nativePackages
        ))
        // (forDarwinSystems (system: (perSystem system).nativePackages));
      devShells = forAllSystems (system: (perSystem system).devShells);

      # Raw overlays for downstream consumers
      overlays.default = final: prev:
        let
          helpers = import ./lib/nix-native.nix { inherit self; pkgs = prev; };
        in
        helpers.overlay final prev;

      # Reusable Library Helper for creating custom brokered shells
      lib = {
        mkHardenedShell = { system, language, version, ... }@args:
          let
            pkgs = import nixpkgs { inherit system; };
            helpers = import ./lib/nix-native.nix { inherit self pkgs; };
          in
          helpers.mkHardenedShell (pkgs.lib.filterAttrs (n: v: n != "system") args);

        graftOntoBase =
          { system
          , fromImage
          , runtime ? null
          , language ? null
          , version ? null
          , tier ? "distroless"
          , tag ? "grafted"
          , name ? null
          , ...
          }@args:
          let
            pkgs = import nixpkgs {
              inherit system;
              config = {
                allowUnfree = true;
              };
              overlays = [
                (import ./overlays/cve-remediation.nix)
              ];
            };
            compiler = import ./lib/build-fleet.nix { inherit pkgs; };
            platformMetadata = import ./lib/platform-metadata.nix;
            imagePrefix = platformMetadata.imagePrefix or "clearcutt";
            parseRuntime = runtimeId:
              if runtimeId == "coreLTS" then {
                language = "core";
                version = "LTS";
              } else
                let
                  parsed = builtins.match "([A-Za-z]+)([0-9].*)" runtimeId;
                in
                if parsed == null then
                  throw "clearcutt.lib.graftOntoBase: runtime must look like java21, python3.15, go1.25, dotnet8, rust1.95, cc15, or coreLTS"
                else {
                  language = builtins.elemAt parsed 0;
                  version = builtins.elemAt parsed 1;
                };
            parsedRuntime =
              if runtime != null then parseRuntime runtime else {};
            languageFinal =
              if language != null then language
              else parsedRuntime.language or (throw "clearcutt.lib.graftOntoBase requires runtime or language");
            versionFinal =
              if version != null then version
              else parsedRuntime.version or (throw "clearcutt.lib.graftOntoBase requires runtime or version");
            imageName = if name == null then "${imagePrefix}-${languageFinal}-${versionFinal}" else name;
            cleanArgs = pkgs.lib.filterAttrs (n: v: !(builtins.elem n [
              "system"
              "name"
              "runtime"
              "language"
              "version"
              "tag"
              "tier"
              "fromImage"
            ])) args;
          in
          compiler.buildFleetImage (cleanArgs // {
            name = imageName;
            tag = tag;
            language = languageFinal;
            version = versionFinal;
            tier = tier;
            fromImage = fromImage;
          });
      };
    };
}
