# ClearCutt Hardened Fleets Declarative Entrypoint

{
  description = "ClearCutt Hardened Base Image Fleets - Declarative, CVE-aware Nix Store Layers";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      linuxSystems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      darwinSystems = [
        "x86_64-darwin"
        "aarch64-darwin"
      ];
      systems = linuxSystems ++ darwinSystems;
      forAllSystems = nixpkgs.lib.genAttrs systems;
      forLinuxSystems = nixpkgs.lib.genAttrs linuxSystems;
      forDarwinSystems = nixpkgs.lib.genAttrs darwinSystems;

      # Runtime-scoped CVE patching uses stock build packages for image
      # assembly, scanners, and dev tooling, then threads patched handles only
      # into package closures that ship inside images.
      cveRemediationOverlay = import ./overlays/cve-remediation.nix;
      dotnetRuntimeOpensslOverlay = final: _prev: {
        # .NET's nixpkgs runtime wrappers bake a top-level openssl path into
        # the package. Isolate that unavoidable override to the package set
        # used for dotnet runtime contents, not the build toolchain.
        openssl_3_6 = final.clearcuttCveOpenssl;
        openssl = final.openssl_3_6;
      };
      nixpkgsConfig = {
        # `allowUnfree` is required for JDKs (Zulu/Oracle) and a few fonts.
        # `allowBroken` was removed: it let Nix produce binaries from
        # packages maintainers had flagged broken, which is incompatible
        # with the project's fixable-CVE gate. If a specific package is
        # incorrectly marked broken, override it inside overlays/cve/.
        allowUnfree = true;
      };
      importBuildNixpkgs = system: import nixpkgs {
        inherit system;
        config = nixpkgsConfig;
      };
      importRuntimeNixpkgs = system: import nixpkgs {
        inherit system;
        config = nixpkgsConfig;
        overlays = [ cveRemediationOverlay ];
      };
      importDotnetRuntimeNixpkgs = system: import nixpkgs {
        inherit system;
        config = nixpkgsConfig;
        overlays = [ cveRemediationOverlay dotnetRuntimeOpensslOverlay ];
      };

      perSystem = system:
      let
        buildPkgs = importBuildNixpkgs system;
        runtimePkgs = importRuntimeNixpkgs system;
        dotnetRuntimePkgs = importDotnetRuntimeNixpkgs system;

        # Host package alignment: build native OCI layers on Linux release
        # runners, and expose native development shells on Darwin for the local
        # inner loop instead of relying on pkgsCross for image builds.
        pkgs = buildPkgs;

        # Import centralized language and runtime registry once per system
        # and thread it into the compiler and native helpers, which would
        # otherwise each re-instantiate it against the same pkgs.
        registry = import ./lib/registry.nix {
          pkgs = runtimePkgs;
          dotnetPkgs = dotnetRuntimePkgs;
        };

        # Import our custom image compiler
        compiler = import ./lib/build-fleet.nix {
          pkgs = buildPkgs;
          inherit runtimePkgs registry;
        };

        # Configured first-class service image specs generated by
        # `clearcutt service scaffold` from clearcutt.fleet.yaml.
        serviceSpecs = import ./lib/service-extensions.nix {};

        # Fork-configurable output identity generated from clearcutt.fleet.yaml.
        platformMetadata = import ./lib/platform-metadata.nix;
        imagePrefix = platformMetadata.imagePrefix or "clearcutt";
        productName = platformMetadata.productName or "ClearCutt";

        # Helper to generate standard package name attributes
        mkPackageName = lang: ver: tier: "${lang}${ver}-${tier}";

        # Matrix specifications - dynamically generated from the central registry
        languages = builtins.filter (lang: lang != "dotnet-runtime") (builtins.attrNames registry.languages);
        versions = builtins.mapAttrs (lang: spec: builtins.attrNames spec.versions) registry.languages;
        tiers = [ "dev" "slim" "distroless" ];

        # Generate image package outputs for the Linux build systems only.
        # Darwin still exposes native runtime closures and dev shells, but not
        # OCI image attrs that require Linux container tooling.
        matrixPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.concatMap (ver:
              pkgs.lib.map (tier:
                let
                  attrName = mkPackageName lang ver tier;
                in
                {
                  name = attrName;
                  value = compiler.buildFleetImage {
                    name = "${imagePrefix}-${lang}-${ver}";
                    tag = tier;
                    language = lang;
                    version = ver;
                    inherit tier;
                  };
                }
              ) tiers
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

        servicePackages = pkgs.lib.listToAttrs (
          builtins.map (service: {
            name = service.id;
            value = compiler.buildServiceImage {
              name = "${imagePrefix}-${service.id}";
              tag = "current";
              inherit service;
            };
          }) serviceSpecs
        );

        # Resolve raw, dynamic-link-patched matrix runtimes
        nativeHelpers = import ./lib/nix-native.nix { inherit self registry; pkgs = runtimePkgs; };

        # Generate a set of raw, dynamic-link-patched matrix runtimes
        # e.g., packages.x86_64-linux.nodejs22-native
        rawPackages = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver:
              let
                attrName = "${lang}${ver}-native";
              in
              {
                name = attrName;
                # Get the first package in the list returned by resolveRawPackages
                value = pkgs.lib.head (nativeHelpers.resolveRawPackages { language = lang; version = ver; });
              }
            ) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) (pkgs.lib.filter (x: x != "core") languages)
        );

        # Per-target hardened dev shells mirror each dev image's runtime closure,
        # so `nix develop .#java21-dev` drops you into the same toolchain the
        # java21:dev image ships. Built natively per host (incl. Darwin) for the
        # local inner loop — this is what `clearcutt dev --nix` resolves to.
        devTargetShells = pkgs.lib.listToAttrs (
          pkgs.lib.concatMap (lang:
            pkgs.lib.map (ver: {
              name = "${lang}${ver}-dev";
              value = nativeHelpers.mkHardenedShell { language = lang; version = ver; };
            }) (pkgs.lib.attrByPath [ lang ] [] versions)
          ) languages
        );

      in
      {
        imagePackages = matrixPackages // servicePackages;
        nativePackages = rawPackages;

        # Default dev shell (build/gating tooling) plus per-target dev shells
        # (devTargetShells) for the local inner loop.
        devShells = {
          default = buildPkgs.mkShell {
            name = "${imagePrefix}-dev-shell";

            # System tools required for local builds, scanning, and inspection,
            # plus the contributor toolchains for the Go CLI and the Astro site.
            buildInputs = [
              buildPkgs.git
              buildPkgs.curl
              buildPkgs.patchelf
              buildPkgs.cosign
              buildPkgs.trivy
              buildPkgs.grype
              buildPkgs.syft
              buildPkgs.skopeo
              buildPkgs.container-structure-test
              buildPkgs.go
              buildPkgs.gopls
              buildPkgs.nodejs
            ];

            shellHook = ''
              if [ -f ${./lib/credential-broker.sh} ]; then
                source ${./lib/credential-broker.sh}
                install_credential_broker_trap
              fi
            '';
          };
        } // devTargetShells;
      };
      # Evaluate each system exactly once: packages and devShells previously
      # called perSystem independently, paying for the nixpkgs import and
      # matrix construction twice per system.
      evaluated = forAllSystems perSystem;
    in
    {
      packages =
        (forLinuxSystems (system:
          evaluated.${system}.imagePackages // evaluated.${system}.nativePackages
        ))
        // (forDarwinSystems (system: evaluated.${system}.nativePackages));
      devShells = forAllSystems (system: evaluated.${system}.devShells);

      # The fleet's CVE patch set, exported standalone so downstreams can
      # apply or audit the remediations directly. It exposes clearcuttCve*
      # handles without rebinding top-level build-toolchain packages.
      overlays.cveRemediation = cveRemediationOverlay;

      # Raw overlay for downstream consumers. The CVE remediation overlay is
      # composed in first so clearcuttCve* handles are available to consumers,
      # but top-level nixpkgs attrs stay stock unless a consumer opts into a
      # patched runtime handle explicitly.
      overlays.default = nixpkgs.lib.composeManyExtensions [
        cveRemediationOverlay
        (final: prev:
          let
            helpers = import ./lib/nix-native.nix { inherit self; pkgs = prev; };
          in
          helpers.overlay final prev)
      ];

      # Reusable Library Helper for creating custom brokered shells
      lib = {
        # Registry truth surface: the flat list of runtime line ids the
        # registry actually compiles ("coreLTS", "java21", "python3.13", ...),
        # mirroring the flake's own image-matrix exclusions (dotnet-runtime is
        # a virtual overlay-only line filtered out of `languages` above).
        # Consumed by tests/verify.sh's registry↔fleet drift gate so
        # clearcutt.fleet.yaml `matrix.languages` can never silently diverge
        # from lib/registry.nix again. Listing attr names never forces the
        # package values, so this stays cheap and system-independent.
        runtimeLines =
          let
            pkgs = import nixpkgs {
              system = "x86_64-linux";
              config.allowUnfree = true;
            };
            registry = import ./lib/registry.nix { inherit pkgs; };
            imageLanguages = builtins.filter (lang: lang != "dotnet-runtime")
              (builtins.attrNames registry.languages);
          in
          nixpkgs.lib.concatMap (lang:
            map (ver: "${lang}${ver}")
              (builtins.attrNames registry.languages.${lang}.versions)
          ) imageLanguages;

        mkHardenedShell = { system, language, version, ... }@args:
          let
            runtimePkgs = importRuntimeNixpkgs system;
            dotnetPkgs = importDotnetRuntimeNixpkgs system;
            registry = import ./lib/registry.nix { pkgs = runtimePkgs; inherit dotnetPkgs; };
            helpers = import ./lib/nix-native.nix { inherit self registry; pkgs = runtimePkgs; };
          in
          helpers.mkHardenedShell (runtimePkgs.lib.filterAttrs (n: v: n != "system") args);

        graftOntoBase =
          { system
          , fromImage
          , runtime ? null
          , language ? null
          , version ? null
          , tier ? "distroless"
          , tag ? "grafted"
          , name ? null
          , ...
          }@args:
          let
            buildPkgs = importBuildNixpkgs system;
            runtimePkgs = importRuntimeNixpkgs system;
            dotnetPkgs = importDotnetRuntimeNixpkgs system;
            registry = import ./lib/registry.nix { inherit dotnetPkgs; pkgs = runtimePkgs; };
            compiler = import ./lib/build-fleet.nix { pkgs = buildPkgs; inherit runtimePkgs registry; };
            platformMetadata = import ./lib/platform-metadata.nix;
            imagePrefix = platformMetadata.imagePrefix or "clearcutt";
            parseRuntime = runtimeId:
              if runtimeId == "coreLTS" then {
                language = "core";
                version = "LTS";
              } else
                let
                  parsed = builtins.match "([A-Za-z]+)([0-9].*)" runtimeId;
                in
                if parsed == null then
                  throw "clearcutt.lib.graftOntoBase: runtime must look like java21, python3.15, go1.25, dotnet8, rust1.95, cc15, or coreLTS"
                else {
                  language = builtins.elemAt parsed 0;
                  version = builtins.elemAt parsed 1;
                };
            parsedRuntime =
              if runtime != null then parseRuntime runtime else {};
            languageFinal =
              if language != null then language
              else parsedRuntime.language or (throw "clearcutt.lib.graftOntoBase requires runtime or language");
            versionFinal =
              if version != null then version
              else parsedRuntime.version or (throw "clearcutt.lib.graftOntoBase requires runtime or version");
            imageName = if name == null then "${imagePrefix}-${languageFinal}-${versionFinal}" else name;
            cleanArgs = buildPkgs.lib.filterAttrs (n: v: !(builtins.elem n [
              "system"
              "name"
              "runtime"
              "language"
              "version"
              "tag"
              "tier"
              "fromImage"
            ])) args;
          in
          compiler.buildFleetImage (cleanArgs // {
            name = imageName;
            tag = tag;
            language = languageFinal;
            version = versionFinal;
            tier = tier;
            fromImage = fromImage;
          });
      };

      # Closure-purity security gate for `nix flake check`, Linux-only because
      # the OCI image matrix is only exposed for Linux systems. For each
      # representative distroless image, closureInfo materializes the full
      # runtime closure of the image's contents and
      # tests/closure-purity-check.py fails the build if that closure provides
      # interactive shells (bin/sh|bash|ash|dash), package-manager binaries
      # (npm, npx, corepack, pip*, apk, dpkg, rpm), or setuid/setgid files —
      # honoring the same explained-exception allowlist
      # (tests/closure-purity-allowlist.txt) as the verify.sh image gate, so
      # a residual finding is consciously accepted rather than silently
      # weakening the gate. Add coverage by appending to closurePurityTargets.
      #
      # Runtime-patch completeness gate (the security keystone of
      # runtime-scoped CVE patching). For each representative image — slim AND
      # distroless, because the slim tier also ships the openssl-linked runtime
      # — closureInfo materializes the SHIPPED runtime closure of the image's
      # contents (never a .drv build closure: under runtime-scoped patching the
      # build-time openssl is intentionally stock, so a build-graph walk would
      # false-positive). tests/closure-cve-check.py then fails the build if any
      # store path is an openssl/sqlite below the committed floor in
      # tests/runtime-dep-floor.json — default-deny, so stock 3.6.2 and the
      # unpatched older majors (openssl_3_5, openssl_3) are caught too. Add
      # coverage by appending to runtimePatchTargets.
      checks = forLinuxSystems (system:
        let
          checkPkgs = import nixpkgs { inherit system; };
          closurePurityTargets = [
            "coreLTS-distroless"
            "node22-distroless"
            "java21-distroless"
            "python3.13-distroless"
          ];
          runtimePatchTargets = [
            "coreLTS-slim"
            "coreLTS-distroless"
            "node22-slim"
            "node22-distroless"
            "java21-slim"
            "java21-distroless"
            "python3.13-slim"
            "python3.13-distroless"
          ];
          mkClosurePurityCheck = attrName:
            let
              image = self.packages.${system}.${attrName};
              closure = checkPkgs.closureInfo { rootPaths = image.clearcuttContents; };
            in
            checkPkgs.runCommand "closure-purity-${attrName}"
              {
                nativeBuildInputs = [ checkPkgs.python3 ];
              } ''
              python3 ${./tests/closure-purity-check.py} \
                --store-paths ${closure}/store-paths \
                --allowlist ${./tests/closure-purity-allowlist.txt}
              touch $out
            '';
          mkRuntimePatchCheck = attrName:
            let
              image = self.packages.${system}.${attrName};
              closure = checkPkgs.closureInfo { rootPaths = image.clearcuttContents; };
            in
            checkPkgs.runCommand "runtime-patch-completeness-${attrName}"
              {
                nativeBuildInputs = [ checkPkgs.python3 ];
              } ''
              python3 ${./tests/closure-cve-check.py} \
                --store-paths ${closure}/store-paths \
                --floor ${./tests/runtime-dep-floor.json}
              touch $out
            '';
        in
        (nixpkgs.lib.genAttrs
          (map (target: "closure-purity-${target}") closurePurityTargets)
          (name: mkClosurePurityCheck (nixpkgs.lib.removePrefix "closure-purity-" name)))
        // (nixpkgs.lib.genAttrs
          (map (target: "runtime-patch-completeness-${target}") runtimePatchTargets)
          (name: mkRuntimePatchCheck (nixpkgs.lib.removePrefix "runtime-patch-completeness-" name)))
      );
    };
}
