package certify

// runtimecve.go is the native-Go port of core/tests/closure-cve-check.py, the
// runtime-patch completeness gate. It proves no UNKNOWN build of a
// CVE-remediated crypto dependency (openssl/sqlite) ships inside a production
// image. It walks the SHIPPED closure — never a .drv build closure — and
// default-denies any tracked crypto store path whose IDENTITY (its store path,
// `<hash>-<name>`) is not on the committed known-good allowlist.
//
// Provenance, not version. Earlier this gate compared the shipped version to a
// numeric floor (openssl >= 3.6.3). That fought the scanner: it forced a
// version-bump rebuild just to make the version string clear the floor. The
// real Nix security model patches openssl IN PLACE (often without bumping the
// version) and substitutes the fixed build from cache. So the gate now asserts
// the patch-state by IDENTITY: a shipped openssl/sqlite passes iff its exact
// store path is one the fleet resolved and provenance-stamped as known-good
// (core/tests/runtime-dep-floor.json, generated by
// `clearcutt remediation generate-crypto-allowlist`). A patched-not-bumped
// openssl-3.6.2 with the known-good identity PASSES; any off-allowlist crypto
// path — including a higher version we did not vet — FAILS (default-deny).

import (
	"archive/tar"
	"encoding/json"
	"fmt"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
)

// RuntimeFloor is the parsed runtime-dep-floor.json: the known-good crypto
// identity allowlist. Per tracked dep (openssl/sqlite) it holds the set of store
// components (`<hash>-<name>`) the fleet vetted as the patched build, plus the
// anchored matcher built from the dep names so the two cannot drift. (The type
// and file keep their historical "floor" names — the gate's CONSUMERS are
// unchanged — but the model is now an identity allowlist, not a version floor.)
type RuntimeFloor struct {
	deps  map[string]*depAllowlist
	names []string // sorted dep names
	depRe *regexp.Regexp
}

// depAllowlist is one tracked dep's known-good identity set.
type depAllowlist struct {
	allowed map[string]bool // set of known-good store components "<hash>-<name>"
	cve     string          // the CVE this dep is remediated for (evidence)
}

// RuntimeCveViolation is one shipped crypto store path that is not allowlisted.
type RuntimeCveViolation struct {
	Path    string
	Message string
}

// RuntimeCveResult is the outcome of a runtime-patch completeness scan.
type RuntimeCveResult struct {
	Violations []RuntimeCveViolation // sorted by message
	Tracked    []string              // "openssl (12 known-good)", ... for the clean summary
}

// Clean reports whether every shipped, tracked crypto path is allowlisted.
func (r RuntimeCveResult) Clean() bool { return len(r.Violations) == 0 }

// allowlistFile is the on-disk schema of runtime-dep-floor.json. Only deps[].name
// and deps[].knownGood[].storePath are read by the gate; the cve/provenance/
// version/system/output siblings are recorded evidence.
type allowlistFile struct {
	Deps []allowlistDep `json:"deps"`
}

type allowlistDep struct {
	Name      string               `json:"name"`
	CVE       string               `json:"cve"`
	KnownGood []allowlistKnownGood `json:"knownGood"`
	// MinVersion is accepted (and rejected) only to give a precise error when an
	// old version-floor file is loaded against the identity gate.
	MinVersion string `json:"minVersion,omitempty"`
}

type allowlistKnownGood struct {
	StorePath string `json:"storePath"`
	System    string `json:"system,omitempty"`
	Output    string `json:"output,omitempty"`
	Version   string `json:"version,omitempty"`
}

// LoadRuntimeDepFloor parses runtime-dep-floor.json into the identity allowlist.
// A missing, empty, malformed, or legacy version-floor file is a hard error: a
// silently-empty allowlist makes the default-deny gate vacuous.
func LoadRuntimeDepFloor(pathName string) (*RuntimeFloor, error) {
	if pathName == "" {
		return nil, fmt.Errorf("runtime-dep-floor is required: pass --floor FILE")
	}
	data, err := os.ReadFile(pathName)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("runtime-dep-floor file not found: %s", pathName)
		}
		return nil, err
	}
	var doc allowlistFile
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("runtime-dep-floor %s: invalid JSON: %w", pathName, err)
	}
	if len(doc.Deps) == 0 {
		return nil, fmt.Errorf("runtime-dep-floor %s: expected a non-empty 'deps' list of {name, knownGood[]}", pathName)
	}

	deps := make(map[string]*depAllowlist, len(doc.Deps))
	for _, d := range doc.Deps {
		name := strings.TrimSpace(d.Name)
		if name == "" {
			return nil, fmt.Errorf("runtime-dep-floor %s: every dep needs a 'name'", pathName)
		}
		if len(d.KnownGood) == 0 {
			// A legacy {name, minVersion} entry has no knownGood — fail with a
			// precise migration hint rather than a vacuous gate.
			if strings.TrimSpace(d.MinVersion) != "" {
				return nil, fmt.Errorf("runtime-dep-floor %s: dep %q uses the retired {name, minVersion} version-floor model; regenerate with `clearcutt remediation generate-crypto-allowlist`", pathName, name)
			}
			return nil, fmt.Errorf("runtime-dep-floor %s: dep %q has an empty 'knownGood' identity list; a vacuous allowlist makes the gate fail open", pathName, name)
		}
		da := &depAllowlist{allowed: map[string]bool{}, cve: strings.TrimSpace(d.CVE)}
		for _, kg := range d.KnownGood {
			component := normalizeStoreComponent(kg.StorePath)
			if component == "" {
				return nil, fmt.Errorf("runtime-dep-floor %s: dep %q has a knownGood entry with an empty/invalid storePath %q", pathName, name, kg.StorePath)
			}
			// Guard against an identity filed under the wrong dep (e.g. a sqlite
			// path listed under openssl): the hash-stripped name must belong to
			// this dep, or the allowlist silently widens to a different package.
			stripped := stripStoreHash(component)
			if stripped != name && !strings.HasPrefix(stripped, name+"-") {
				return nil, fmt.Errorf("runtime-dep-floor %s: dep %q lists a knownGood storePath %q whose package is not %q", pathName, name, component, name)
			}
			da.allowed[component] = true
		}
		deps[name] = da
	}

	names := make([]string, 0, len(deps))
	for name := range deps {
		names = append(names, name)
	}
	sort.Strings(names)

	quoted := make([]string, len(names))
	for i, n := range names {
		quoted[i] = regexp.QuoteMeta(n)
	}
	// Anchor <dep>-<dotted-numeric>[-<output>]: the dotted-numeric version group
	// plus the optional bare-lowercase nix output suffix is what identifies a
	// tracked crypto store path while skipping .drv / .tar.gz / .zip / .patch
	// artifacts. The version is NOT compared — only used to recognize the path.
	depRe, err := regexp.Compile("^(" + strings.Join(quoted, "|") + ")-([0-9][0-9.]*)(?:-[a-z]+)?$")
	if err != nil {
		return nil, fmt.Errorf("runtime-dep-floor %s: building matcher: %w", pathName, err)
	}

	return &RuntimeFloor{deps: deps, names: names, depRe: depRe}, nil
}

// normalizeStoreComponent reduces a store path or bare component to the
// `<hash>-<name>` store component the gate compares against. Accepts a full
// `/nix/store/<hash>-<name>[/...]`, a bare `<hash>-<name>`, or either with a
// trailing slash.
func normalizeStoreComponent(raw string) string {
	s := strings.TrimSpace(raw)
	if s == "" {
		return ""
	}
	s = strings.TrimRight(s, "/")
	if i := strings.Index(s, "nix/store/"); i >= 0 {
		s = s[i+len("nix/store/"):]
	}
	// Keep only the top store component, dropping any in-path suffix.
	if i := strings.IndexByte(s, '/'); i >= 0 {
		s = s[:i]
	}
	if s == "" || !strings.Contains(s, "-") {
		return ""
	}
	return s
}

// Tracked returns "<dep> (N known-good)" strings (sorted) for the clean summary.
func (f *RuntimeFloor) Tracked() []string {
	out := make([]string, len(f.names))
	for i, n := range f.names {
		out[i] = fmt.Sprintf("%s (%d known-good)", n, len(f.deps[n].allowed))
	}
	return out
}

// evaluateComponent returns a violation message for a FULL store component
// (`<hash>-<name>`), or "" when it is not a tracked crypto path (no match /
// artifact skip) or its identity is on the known-good allowlist.
func (f *RuntimeFloor) evaluateComponent(component string) string {
	stripped := stripStoreHash(component)
	m := f.depRe.FindStringSubmatch(stripped)
	if m == nil {
		return ""
	}
	dep := m[1]
	da := f.deps[dep]
	if da.allowed[component] {
		return ""
	}
	return fmt.Sprintf("image ships an off-allowlist %s identity %s — not a provenance-allowlisted known-good build; cannot prove it is patched", dep, component)
}

// runtimeCveFindings tracks violations keyed by store path so layer whiteouts
// can drop findings shadowed by later layers, and dedups store components.
type runtimeCveFindings struct {
	violations map[string]string
	seen       map[string]bool
}

func newRuntimeCveFindings() *runtimeCveFindings {
	return &runtimeCveFindings{violations: map[string]string{}, seen: map[string]bool{}}
}

func (rf *runtimeCveFindings) inspectMember(hdr *tar.Header, floor *RuntimeFloor) {
	name := normalizeMemberName(hdr.Name)
	if name == "" {
		return
	}
	base := path.Base(name)
	if strings.HasPrefix(base, ".wh.") {
		// Violations are keyed by "/nix/store/<comp>" (leading slash), so the
		// whiteout-discard key needs the same leading slash to match. A
		// whiteout-ed store path is not in the shipped rootfs.
		delete(rf.violations, "/"+path.Join(path.Dir(name), base[len(".wh."):]))
		return
	}
	m := closureStoreCompRe.FindStringSubmatch(name)
	if m == nil {
		return
	}
	component := m[1]
	storePath := "/nix/store/" + component
	if rf.seen[storePath] {
		return
	}
	rf.seen[storePath] = true
	if msg := floor.evaluateComponent(component); msg != "" {
		rf.violations[storePath] = fmt.Sprintf("%s at %s", msg, storePath)
	}
}

func (rf *runtimeCveFindings) result(floor *RuntimeFloor) RuntimeCveResult {
	violations := make([]RuntimeCveViolation, 0, len(rf.violations))
	for p, msg := range rf.violations {
		violations = append(violations, RuntimeCveViolation{Path: p, Message: msg})
	}
	sort.Slice(violations, func(i, j int) bool { return violations[i].Message < violations[j].Message })
	return RuntimeCveResult{Violations: violations, Tracked: floor.Tracked()}
}

// ScanImageArchiveForRuntimeCve walks every layer of a docker-save or
// OCI-layout image archive and returns the runtime-patch completeness result.
func ScanImageArchiveForRuntimeCve(archivePath string, floor *RuntimeFloor) (RuntimeCveResult, error) {
	rf := newRuntimeCveFindings()
	if err := walkImageLayers(archivePath, func(hdr *tar.Header) error {
		rf.inspectMember(hdr, floor)
		return nil
	}); err != nil {
		return RuntimeCveResult{}, err
	}
	return rf.result(floor), nil
}

// ScanStorePathsForRuntimeCve evaluates each store path in a closureInfo
// store-paths file instead of an image archive.
func ScanStorePathsForRuntimeCve(storePathsFile string, floor *RuntimeFloor) (RuntimeCveResult, error) {
	data, err := os.ReadFile(storePathsFile)
	if err != nil {
		return RuntimeCveResult{}, err
	}
	var storePaths []string
	for _, line := range strings.Split(string(data), "\n") {
		if s := strings.TrimSpace(line); s != "" {
			storePaths = append(storePaths, s)
		}
	}
	if len(storePaths) == 0 {
		return RuntimeCveResult{}, fmt.Errorf("store paths file is empty: %s", storePathsFile)
	}

	rf := newRuntimeCveFindings()
	for _, storePath := range storePaths {
		component := path.Base(strings.TrimRight(storePath, "/"))
		if msg := floor.evaluateComponent(component); msg != "" {
			rf.violations[storePath] = fmt.Sprintf("%s at %s", msg, storePath)
		}
	}
	return rf.result(floor), nil
}
