package platformsource

import (
	"archive/zip"
	"bytes"
	"embed"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Only archive/README.md is committed; archive/source.zip is generated by
// internal/genplatformsource (or `fleet build-cli-assets`) and gitignored so
// the repo never carries a multi-megabyte binary that goes stale on every
// commit. Embedding the directory instead of the zip keeps a bare `go build`
// of a fresh clone compiling; binaries built without the generated archive
// report ErrNotEmbedded and `platform new` falls back to a release archive URL.
//
//go:embed archive
var embedded embed.FS

// ErrNotEmbedded reports that this binary was built without the generated
// reference source archive (e.g. a bare `go build` instead of `make cli-build`).
var ErrNotEmbedded = errors.New("platform source archive not embedded in this binary")

func Bytes() ([]byte, error) {
	raw, err := embedded.ReadFile("archive/source.zip")
	if err != nil {
		return nil, fmt.Errorf("%w; run `go run ./internal/platformsource/internal/genplatformsource` in cli/ (or build via `make cli-build`) to generate it", ErrNotEmbedded)
	}
	return raw, nil
}

func Materialize() (string, func(), error) {
	raw, err := Bytes()
	if err != nil {
		return "", func() {}, err
	}
	tmpDir, err := os.MkdirTemp("", "clearcutt-embedded-platform-source-*")
	if err != nil {
		return "", func() {}, err
	}
	cleanup := func() { _ = os.RemoveAll(tmpDir) }
	reader, err := zip.NewReader(bytes.NewReader(raw), int64(len(raw)))
	if err != nil {
		cleanup()
		return "", func() {}, fmt.Errorf("open embedded platform source archive: %w", err)
	}
	if err := unzip(reader, tmpDir); err != nil {
		cleanup()
		return "", func() {}, err
	}
	return tmpDir, cleanup, nil
}

// FindRepoRoot walks up from start looking for the ClearCutt monorepo root
// (identified by clearcutt.fleet.yaml alongside go.work).
func FindRepoRoot(start string) (string, bool) {
	wd := start
	for {
		// Accept either config name so an unmigrated checkout still resolves.
		if hasClearCuttConfig(wd) {
			if _, err := os.Stat(filepath.Join(wd, "go.work")); err == nil {
				return wd, true
			}
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", false
		}
		wd = parent
	}
}

// ArchivePath returns the on-disk location of the generated source archive
// for the repo rooted at root.
func ArchivePath(root string) string {
	return filepath.Join(root, "cli", "internal", "platformsource", "archive", "source.zip")
}

func unzip(reader *zip.Reader, dir string) error {
	for _, file := range reader.File {
		clean := filepath.Clean(filepath.FromSlash(file.Name))
		if clean == "." || filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return fmt.Errorf("embedded platform source archive contains unsafe path %q", file.Name)
		}
		target := filepath.Join(dir, clean)
		if file.FileInfo().IsDir() {
			if err := os.MkdirAll(target, file.Mode().Perm()); err != nil {
				return err
			}
			continue
		}
		if !file.FileInfo().Mode().IsRegular() {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		src, err := file.Open()
		if err != nil {
			return err
		}
		dst, err := os.OpenFile(target, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, file.Mode().Perm())
		if err != nil {
			_ = src.Close()
			return err
		}
		_, copyErr := io.Copy(dst, src)
		closeErr := dst.Close()
		_ = src.Close()
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
	}
	return nil
}

// hasClearCuttConfig reports whether a directory holds a ClearCutt config under
// either the current or the legacy name.
func hasClearCuttConfig(dir string) bool {
	for _, name := range []string{"clearcutt.yaml", "clearcutt.fleet.yaml"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
			return true
		}
	}
	return false
}
