# Generated by `clearcutt fleet compile` from clearcutt.fleet.yaml.
# Resolved fleet build set: the concrete (language, version, tier) image
# cells, their lifecycle, and the realized-closure gate targets. This file is
# DATA, not logic — the hardened per-runtime recipes stay in lib/registry.nix.
# Do not edit by hand; regenerate with `clearcutt fleet compile`. CI fails on
# drift via `clearcutt fleet compile --check`.

{
  systems = [ "x86_64-linux" "aarch64-linux" ];
  tiers = [ "dev" "slim" "distroless" ];

  cells = [
    { line = "coreLTS"; language = "core"; version = "LTS"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "coreLTS"; language = "core"; version = "LTS"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "coreLTS"; language = "core"; version = "LTS"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "java21"; language = "java"; version = "21"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "java21"; language = "java"; version = "21"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "java21"; language = "java"; version = "21"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "java25"; language = "java"; version = "25"; tier = "dev"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "java25"; language = "java"; version = "25"; tier = "slim"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "java25"; language = "java"; version = "25"; tier = "distroless"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "node24"; language = "node"; version = "24"; tier = "dev"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "node24"; language = "node"; version = "24"; tier = "slim"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "node24"; language = "node"; version = "24"; tier = "distroless"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "python3.13"; language = "python"; version = "3.13"; tier = "dev"; lifecycle = { status = "active"; support = "current"; productionAllowed = false; }; }
    { line = "python3.13"; language = "python"; version = "3.13"; tier = "slim"; lifecycle = { status = "active"; support = "current"; productionAllowed = true; }; }
    { line = "python3.13"; language = "python"; version = "3.13"; tier = "distroless"; lifecycle = { status = "active"; support = "current"; productionAllowed = true; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "go1.25"; language = "go"; version = "1.25"; tier = "dev"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "go1.25"; language = "go"; version = "1.25"; tier = "slim"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "go1.25"; language = "go"; version = "1.25"; tier = "distroless"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "dotnet8"; language = "dotnet"; version = "8"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "dotnet8"; language = "dotnet"; version = "8"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "dotnet8"; language = "dotnet"; version = "8"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "dotnet10"; language = "dotnet"; version = "10"; tier = "dev"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "dotnet10"; language = "dotnet"; version = "10"; tier = "slim"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "dotnet10"; language = "dotnet"; version = "10"; tier = "distroless"; lifecycle = { status = "preview"; support = "preview"; productionAllowed = false; }; }
    { line = "rust1.95"; language = "rust"; version = "1.95"; tier = "dev"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "rust1.95"; language = "rust"; version = "1.95"; tier = "slim"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "rust1.95"; language = "rust"; version = "1.95"; tier = "distroless"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "cc15"; language = "cc"; version = "15"; tier = "dev"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "cc15"; language = "cc"; version = "15"; tier = "slim"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
    { line = "cc15"; language = "cc"; version = "15"; tier = "distroless"; lifecycle = { status = "experimental"; support = "unsupported"; productionAllowed = false; }; }
  ];

  closurePurityTargets = [
    "coreLTS-distroless"
    "java21-distroless"
    "java25-distroless"
    "node22-distroless"
    "node24-distroless"
    "python3.13-distroless"
    "python3.14-distroless"
    "dotnet8-distroless"
    "dotnet10-distroless"
  ];

  runtimePatchTargets = [
    "coreLTS-slim"
    "coreLTS-distroless"
    "java21-slim"
    "java21-distroless"
    "java25-slim"
    "java25-distroless"
    "node22-slim"
    "node22-distroless"
    "node24-slim"
    "node24-distroless"
    "python3.13-slim"
    "python3.13-distroless"
    "python3.14-slim"
    "python3.14-distroless"
    "dotnet8-slim"
    "dotnet8-distroless"
    "dotnet10-slim"
    "dotnet10-distroless"
  ];
}
