# Generated by `clearcutt fleet compile` from clearcutt.yaml.
# Resolved fleet build set: the concrete (language, version, tier) image
# cells, their lifecycle, and the realized-closure gate targets. This file is
# DATA, not logic — the hardened per-runtime recipes stay in lib/registry.nix.
# Do not edit by hand; regenerate with `clearcutt fleet compile`. CI fails on
# drift via `clearcutt fleet compile --check`.

{
  systems = [ "x86_64-linux" "aarch64-linux" ];
  tiers = [ "dev" "slim" "distroless" ];

  cells = [
    { line = "java25"; language = "java"; version = "25"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "java25"; language = "java"; version = "25"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "java25"; language = "java"; version = "25"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
  ];

  closurePurityTargets = [
    "java25-distroless"
  ];
}
