# Generated by `clearcutt fleet compile` from clearcutt.fleet.yaml.
# Resolved fleet build set: the concrete (language, version, tier) image
# cells, their lifecycle, and the realized-closure gate targets. This file is
# DATA, not logic — the hardened per-runtime recipes stay in lib/registry.nix.
# Do not edit by hand; regenerate with `clearcutt fleet compile`. CI fails on
# drift via `clearcutt fleet compile --check`.

{
  systems = [ "x86_64-linux" "aarch64-linux" ];
  tiers = [ "dev" "slim" "distroless" ];

  cells = [
    { line = "java21"; language = "java"; version = "21"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "java21"; language = "java"; version = "21"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "java21"; language = "java"; version = "21"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "node22"; language = "node"; version = "22"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "python3.14"; language = "python"; version = "3.14"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = true; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "dev"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "slim"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
    { line = "go1.26"; language = "go"; version = "1.26"; tier = "distroless"; lifecycle = { status = "active"; support = "lts"; productionAllowed = false; }; }
  ];

  closurePurityTargets = [
    "java21-distroless"
    "node22-distroless"
    "python3.14-distroless"
  ];
}
