# Generated by `clearcutt platform init`.
# Keep this aligned with clearcutt.yaml when operating a fork.

{
  repoPath = "northcutted/clearcutt";
  sourceURL = "https://github.com/northcutted/clearcutt";
  productName = "ClearCutt";
  imagePrefix = "clearcutt";
  vendor = "ClearCutt";
  authors = "ClearCutt maintainers";
}
