# Generated by `clearcutt runtime scaffold` from clearcutt.fleet.yaml.
# Built-in runtime lines live in registry.nix; custom runtime lines are merged
# here so fleet owners can extend the product surface through the CLI.

{ pkgs, getPkg, removeNpm ? null }:

{
  languages = {};
}
