# Generated by `clearcutt service scaffold` from clearcutt.yaml.
# Built-in service templates are expanded here so fleet owners can add
# platform service images through the CLI without learning Nix internals.

{ }:

[
  {
    id = "oauth2-proxy7";
    template = "oauth2-proxy";
    version = "7";
    description = "oauth2-proxy authentication gateway service image";
    packageCandidates = [ "oauth2-proxy" ];
    ports = [
      { name = "http"; port = 4180; protocol = "tcp"; }
    ];
    stateful = false;
    entrypoint = [ "oauth2-proxy" ];
    smoke = [ "oauth2-proxy --version" ];
    lifecycle = {
      status = "preview";
      support = "current";
    };
    productionAllowed = false;
  }
  {
    id = "postgres16";
    template = "postgres";
    version = "16";
    description = "Postgres database service image";
    packageCandidates = [ "postgresql_16" ];
    ports = [
      { name = "postgres"; port = 5432; protocol = "tcp"; }
    ];
    stateful = true;
    dataDirs = [ "/var/lib/postgresql/data" ];
    env = [ "PGDATA=/var/lib/postgresql/data" ];
    entrypoint = [ "clearcutt-postgres-entrypoint" ];
    smoke = [ "postgres --version" "initdb --version" "pg_isready --version" ];
    lifecycle = {
      status = "preview";
      support = "current";
    };
    productionAllowed = false;
  }
  {
    id = "valkey8";
    template = "valkey";
    version = "8";
    description = "Valkey in-memory data store service image";
    packageCandidates = [ "valkey" ];
    ports = [
      { name = "redis"; port = 6379; protocol = "tcp"; }
    ];
    stateful = true;
    dataDirs = [ "/data" ];
    entrypoint = [ "valkey-server" ];
    smoke = [ "valkey-server --version" "valkey-cli --version" ];
    lifecycle = {
      status = "preview";
      support = "current";
    };
    productionAllowed = false;
  }
]
